const compDes = [
  {
    tags: {},
    filePath: '/Users/lujiajianb27070/code/sirius-desktop/packages/web-common/src/components/UI/PageHeader/index.tsx',
    description: '',
    displayName: 'PageHeader',
    methods: [],
    props: {
      backIcon: {
        defaultValue: { value: true },
        description: '是否显示返回按钮',
        name: 'backIcon',
        parent: { fileName: 'sirius-desktop/packages/web-common/src/components/UI/PageHeader/pageHeader.tsx', name: 'PageHeaderProps' },
        declarations: [{ fileName: 'sirius-desktop/packages/web-common/src/components/UI/PageHeader/pageHeader.tsx', name: 'PageHeaderProps' }],
        required: false,
        type: { name: 'ReactNode' },
      },
      title: {
        defaultValue: null,
        description: '自定义标题文字',
        name: 'title',
        parent: { fileName: 'sirius-desktop/packages/web-common/src/components/UI/PageHeader/pageHeader.tsx', name: 'PageHeaderProps' },
        declarations: [{ fileName: 'sirius-desktop/packages/web-common/src/components/UI/PageHeader/pageHeader.tsx', name: 'PageHeaderProps' }],
        required: true,
        type: { name: 'string' },
      },
      subTitle: {
        defaultValue: null,
        description: '自定义的二级标题文字（说明文案）',
        name: 'subTitle',
        parent: { fileName: 'sirius-desktop/packages/web-common/src/components/UI/PageHeader/pageHeader.tsx', name: 'PageHeaderProps' },
        declarations: [{ fileName: 'sirius-desktop/packages/web-common/src/components/UI/PageHeader/pageHeader.tsx', name: 'PageHeaderProps' }],
        required: false,
        type: { name: 'string' },
      },
      titleExtraIcon: {
        defaultValue: null,
        description: '标题和二级标题中间的图标',
        name: 'titleExtraIcon',
        parent: { fileName: 'sirius-desktop/packages/web-common/src/components/UI/PageHeader/pageHeader.tsx', name: 'PageHeaderProps' },
        declarations: [{ fileName: 'sirius-desktop/packages/web-common/src/components/UI/PageHeader/pageHeader.tsx', name: 'PageHeaderProps' }],
        required: false,
        type: { name: 'ReactNode' },
      },
      extra: {
        defaultValue: null,
        description: '操作区，位于 title 行的行尾',
        name: 'extra',
        parent: { fileName: 'sirius-desktop/packages/web-common/src/components/UI/PageHeader/pageHeader.tsx', name: 'PageHeaderProps' },
        declarations: [{ fileName: 'sirius-desktop/packages/web-common/src/components/UI/PageHeader/pageHeader.tsx', name: 'PageHeaderProps' }],
        required: false,
        type: { name: 'ReactNode' },
      },
      bgTransparent: {
        defaultValue: { value: false },
        description: '背景是否透明',
        name: 'bgTransparent',
        parent: { fileName: 'sirius-desktop/packages/web-common/src/components/UI/PageHeader/pageHeader.tsx', name: 'PageHeaderProps' },
        declarations: [{ fileName: 'sirius-desktop/packages/web-common/src/components/UI/PageHeader/pageHeader.tsx', name: 'PageHeaderProps' }],
        required: false,
        type: { name: 'boolean' },
      },
      className: {
        defaultValue: { value: '' },
        description: '类名',
        name: 'className',
        parent: { fileName: 'sirius-desktop/packages/web-common/src/components/UI/PageHeader/pageHeader.tsx', name: 'PageHeaderProps' },
        declarations: [{ fileName: 'sirius-desktop/packages/web-common/src/components/UI/PageHeader/pageHeader.tsx', name: 'PageHeaderProps' }],
        required: false,
        type: { name: 'string' },
      },
      onBack: {
        defaultValue: null,
        description: '返回按钮的点击事件',
        name: 'onBack',
        parent: { fileName: 'sirius-desktop/packages/web-common/src/components/UI/PageHeader/pageHeader.tsx', name: 'PageHeaderProps' },
        declarations: [{ fileName: 'sirius-desktop/packages/web-common/src/components/UI/PageHeader/pageHeader.tsx', name: 'PageHeaderProps' }],
        required: false,
        type: { name: '() => void' },
      },
    },
  },
];
export default compDes;
