export const MenuPermissionV2: Record<string, string> = {
  // 企业设置
  ORG_SETTINGS: '',
  // 任务规则设置
  ORG_SETTINGS_TASK_CENTER_RULE_SETTING: '#enterpriseSetting?page=systemTaskConfig',
  // 话术库
  ORG_SETTINGS_WORD_ART_LIBRARY: '#enterpriseSetting?page=salesPitch',
  // 通知设置
  ORG_SETTINGS_NOTIFY_SETTING: '#enterpriseSetting?page=noticeSetting',
  // 邮件智能标签
  ORG_SETTINGS_AI_TAG_SETTING: '#enterpriseSetting?page=mailTag',
  // WhatsApp账号管理
  ORG_SETTINGS_PEER_SETTING: '#enterpriseSetting?page=insertWhatsApp',
  // 邮件营销模版变量
  ORG_SETTINGS_TMPL_VARIABLE_SETTING: '#enterpriseSetting?page=variables',
  // 邮件营销配额
  ORG_SETTINGS_QUOTA_SETTING: '#enterpriseSetting?page=quota',
  // 往来邮件-授权白名单
  ORG_SETTINGS_WHITELIST_SETTING: '#enterpriseSetting?page=authorizationEmail',
  // 邮件营销发件限制
  ORG_SETTINGS_EMAIL_SEND_QUOTA_SETTING: '#enterpriseSetting?page=marketingSetting',
  // 任务中心
  TASK_CENTER: '',
  // 权限
  PRIVILEGE: '',
  // 工作台
  WORKBENCH: '',
  // 客户管理
  CUSTOMER_MANAGE: '',
  // 推荐
  RECOMMEND: '',
  // 邮件筛选
  PREVIOUS_CONTACT: '#/unitable-crm/autoRecommend',
  // 推荐客户
  CUSTOMER_RECOMMEND: '#/unitable-crm/recommend/list',
  // 授权管理
  PREVIOUS_CONTACT_GRANT_ADMIN: '#/unitable-crm/authorization',
  // 客户
  CONTACT: '',
  // 客户公海
  CONTACT_OPEN_SEA: '#/unitable-crm/custom/public/list',
  // 客户列表
  CONTACT_LIST: '#/unitable-crm/custom/list',
  // 客户标签
  CONTACT_TAG_MANAGE: '#/unitable-crm/custom/label/list',
  // 线索
  CHANNEL: '',
  // 线索列表
  CONTACT_CHANNEL_LIST: '#/unitable-crm/lead/list',
  // 线索公海
  CHANNEL_OPEN_SEA: '#/unitable-crm/lead/public/list',
  // 商机
  COMMERCIAL: '#/unitable-crm/business/list',
  // 商机列表
  CONTACT_COMMERCIAL_LIST: '#/unitable-crm/business/list',
  // 客户履约
  CUSTOMER_PROMISE: '',
  // 商品管理
  PRODUCT: '',
  // 平台商品
  PLATFORM_PRODUCT: '#/unitable-crm/product/platform/list',
  // 本地商品
  LOCAL_PRODUCT: '#/unitable-crm/product/local/list',
  // 供应商管理
  SUPPLIER_MANAGE: '#/unitable-crm/supplier/management',
  // 交易管理
  TRADE_MANAGE: '',
  // 销售订单
  ORDER: '#/unitable-crm/sell-order/list',
  // 品牌首页
  WEBSITE_MAIN_PAGE: '#site?page=brand',
  // 建站管理
  WEBSITE_ADMIN: '',
  // 域名管理
  DOMAIN_ADMIN: '#site?page=myDomain',
  // 信息模版
  DOMAIN_ADMIN_INFO_TEMP: '#site?page=infoTemplate',
  // 我的域名
  DOMAIN_ADMIN_MINE: '#site?page=myDomain',
  // 我的证书
  DOMAIN_ADMIN_MY_CERTIFICATE: '#site?page=myCert',
  // 订单管理
  DOMAIN_ADMIN_ORDER: '#site?page=orderManage',
  // 我的站点
  WEBSITE_ADMIN_MINE: '#site?page=mySite',
  // 海外社媒
  SOCIAL_MEDIA: '',
  // 我的社媒
  SOCIAL_MEDIA_MY: '#site?page=snsAccountBinding',
  // 账号管理
  SOCIAL_MEDIA_ACCOUNT: '#site?page=snsAccountBinding',
  // 营销任务
  SOCIAL_MEDIA_TASK: '#site?page=snsMarketingTask',
  // 营销日历
  SOCIAL_MEDIA_CALENDAR: '#site?page=snsCalendar',
  // 帖子管理
  SOCIAL_MEDIA_POST: '#site?page=snsPostManage',
  // 消息管理
  SOCIAL_MEDIA_MESSAGE: '#site?page=snsMessage',
  // 社媒数据
  SOCIAL_MEDIA_DATA: '#site?page=snsGlobalDataAnalysis',
  // 营销落地页
  WEBSITE_ADMIN_MARKET: '#site?page=market',
  // 文章管理
  ARTICLE_ADMIN: '#site?page=articleList',
  // 文章管理
  ARTICLE_ADMIN_MANAGE: '#site?page=articleList',
  // 分类管理
  ARTICLE_ADMIN_CATAGORY: '#site?page=categoryList',
  // 站点数据
  WEBSITE_ADMIN_DATA: '#site?page=stat',
  // 整体数据
  WEBSITE_OVERALL_DATA: '#site?page=stat',
  // 潜在客户
  WEBSITE_TARGET_CONTACT: '#site?page=siteCustomer',
  // 流量投放
  TRAFFIC_PLACEMENT: '#site?page=trafficDelivery',
  // WA
  WA: '',
  // WhatsApp个人
  WHATSAPP_PERSONAL: '',
  // 客户挖掘
  CUSTOMER_PROSPECTING: '',
  // 数据获客
  DATA_MINING: '',
  //港口搜索
  FREIGHT_FORWARDING_PORT_SEARCH: '#wmData?page=forwarder',
  //工商搜索（国内）
  FREIGHT_FORWARDING_IC_SEARCH: '#wmData?page=industryCommerceSearch',
  //智能搜索（国内）
  FREIGHT_FORWARDING_AI_SEARCH: '#wmData?page=intelligentSearch',
  // 智能推荐
  AI_RECOMMEND: '#wmData?page=smartrcmd',
  // 海关数据
  CUSTOMS: '#wmData?page=customs',
  // 展会买家
  EXHIBITION_BUYER: '#wmData?page=contomfair',
  // 地图搜索
  MAP_SEARCH: '#wmData?page=lbs',
  // 全球搜索
  GLOBAL_SEARCH: '#wmData?page=globalSearch',
  // 社媒搜索
  SOCIAL_MEDIA_SEARCH: '#wmData?page=linkedin',
  // 智能引擎搜索
  AI_SEARCH: '#wmData?page=intelligent',
  // 找客工具
  CUSTOMER_PROSPECTING_TOOL: '',
  // 浏览器插件获客
  BROWSER_PLUGIN_TOOL: '#wmData?page=extension',
  // 邮箱猜想
  EMAIL_ASSOCIATE: '',
  // 市场洞察
  MARKETING_INSIGHT: '',
  // 贸易分析
  TRADE_ANALYSIS: '#wmData?page=tradeAnalysis',
  // 公司订阅
  COMPANY_SUB: '#wmData?page=star',
  // 产品订阅
  PRODUCT_SUB: '#wmData?page=keywords',
  // 客户开发
  CUSTOMER_EXLOIT: '',
  // Facebook营销
  FACEBOOK: '',
  // 主页管理
  FACEBOOK_MY_MAIN_PAGE: '#edm?page=facebookPages',
  // 帖子评论
  FACEBOOK_MY_POST: '#edm?page=facebookPosts',
  // 消息
  FACEBOOK_MSG: '#edm?page=facebookMessage',
  // 手动开发
  MANUAL_EXLOIT: '',
  // 新建发件任务
  NEW_EDM_SEND_TASK: '#intelliMarketing?page=write',
  // 邮箱预热
  EDM_MULTI_ACCOUNT_WARMUP: '#intelliMarketing?page=warmup',
  // 任务列表
  EDM_SENDBOX: '#intelliMarketing?page=index',
  // 多账号开发
  EDM_MULTI_ACCOUNT_INFO: '#intelliMarketing?page=senderRotateList',
  // 营销统计
  MARKET_DATA_STAT: '',
  // 数据统计
  EDM_DATA_STAT: process.env.BUILD_ISELECTRON ? '#edm?page=contact' : '#intelliMarketing?page=addressBookDatastat',
  // 地址簿
  ADDRESS_BOOK: '#intelliMarketing?page=addressBookIndex',
  // whatsapp个人营销
  WHATSAPP_PERSONAL_MARKETING: '',
  // 个人号消息
  WHATSAPP_PERSONAL_MSG: '/personalWhatsapp/',
  // 个人号群发任务
  WHATSAPP_PERSONAL_SEND_TASK: '#intelliMarketing?page=pernsonalJobWhatsApp',
  // whatsapp商业营销
  WHATSAPP_BUSINESS_MARKETING: '',
  // 商业号消息
  WHATSAPP_MSG: '#intelliMarketing?page=whatsAppMessage',
  // 商业号群发任务
  WHATSAPP_SEND_TASK: '#intelliMarketing?page=whatsAppJob',
  // 数据统计
  WHATSAPP_DATA_STAT: '#intelliMarketing?page=whatsAppStatistic',
  // 消息模版
  WHATSAPP_MSG_TPL_SETTING: '#intelliMarketing?page=whatsAppTemplate',
  // 邮件开发辅助工具
  EMAIL_AID_TOOL: '',
  // 邮件模板
  EDM_TEMPLATE: '#intelliMarketing?page=mailTemplate',
  // 草稿列表
  EDM_DRAFT_LIST: '#intelliMarketing?page=drafts',
  // 自动化营销
  AUTO_MARKETING: '#intelliMarketing?page=autoMarketTask',
  // 自动开发
  AUTO_EXLOIT: '',
  // 营销托管任务
  MARKETING_TUTELAGE_TASK: '#intelliMarketing?page=aiHosting',
  // 新建营销托管任
  NEW_MARKETING_TUTELAGE_TASK: '#intelliMarketing?page=aiHostingNew',
  // 会话列表
  WA_CHAT_LIST: '#wa?page=wa',
  // 分享记录
  WA_FILE_SHARE_RECORD: '#wa?page=materielShareList',
  // 访问记录
  WA_FILE_ACCESS_RECORD: '#wa?page=materielVisitList',
  // 文件列表
  WA_FILE_LIST: '#wa?page=materielFileList',
  // 关注列表
  WA_CHAT_EMPHASIS_MANAGE_LIST: '#wa?page=waOperateLog',
  // 联系人分组
  WA_CHAT_CONTACT_GROUP: '#wa?page=contactGroup',
  // 工作量统计
  WA_CHAT_WORKLOAD_STATS: '#wa?page=workloadStats',
  // 群发消息
  WHATSAPP_GROUP_MSG: '#edm?page=multiAccountMessage',
  // 群发群发
  WHATSAPP_MARKETING_GROUP_SEND: '#edm?page=marketBulk',
  // 群发-营销搜索
  WHATSAPP_MARKETING_SEARCH: '#edm?page=marketSearchWhatsApp',
  WHATSAPP_MARKETING_ADD_GROUP: '#edm?page=marketWaGroupHistory',
  SUBSCRIBE_CUSTOMER_LIST: '#edm?page=customerBookList',
  EFFECT_FREIGHT_CHARGE: '#/unitable-crm/price/effective',
  WAITING_APPROVAL_FREIGHT_CHARGE: '#/unitable-crm/price/pending',
};
