export const jsonList = [
  {
    pFunc: '邮箱',
    pFree: '1',
    pPay: '1',
    pLingx: '1',
    children: [
      {
        func: '发信上限',
        free: '30',
        pay: '1000',
        lingxi: '2500',
        titleInfo: '封/天/账号',
      },
      {
        func: '高级搜索',
        free: '0',
        pay: '1',
        lingxi: '1',
      },
      {
        func: '超大附件',
        free: '0',
        pay: '15天有效',
        lingxi: '永久有效',
      },
      {
        func: '添加云文档附件',
        free: '0',
        pay: '0',
        lingxi: '1',
      },
      {
        func: '企业外收件人阅读状态追踪',
        free: '0',
        pay: '0',
        lingxi: '1',
      },
      {
        func: '企业内收件人阅读状态追踪',
        free: '0',
        pay: '1',
        lingxi: '1',
      },
      {
        func: '点赞邮件',
        free: '0',
        pay: '0',
        lingxi: '1',
      },
      {
        func: '@联系人',
        free: '0',
        pay: '0',
        lingxi: '1',
      },
      {
        func: '表扬邮件',
        free: '0',
        pay: '0',
        lingxi: '1',
      },
    ],
  },
  {
    pFunc: '即时消息',
    pFree: '1',
    pPay: '1',
    pLingx: '1',
    children: [
      {
        func: '单聊',
        free: '1',
        pay: '1',
        lingxi: '1',
      },
      {
        func: '群聊',
        free: '1',
        pay: '1',
        lingxi: '1',
      },
      {
        func: '表情回复',
        free: '1',
        pay: '1',
        lingxi: '1',
      },
    ],
  },
  {
    pFunc: '日历',
    pFree: '1',
    pPay: '1',
    pLingx: '1',
    children: [
      {
        func: '新建日历',
        free: '1',
        pay: '1',
        lingxi: '1',
      },
      {
        func: '日程邀约',
        free: '1',
        pay: '1',
        lingxi: '1',
      },
      {
        func: '日程视图',
        free: '1',
        pay: '1',
        lingxi: '1',
      },
      {
        func: '共享/订阅日历',
        free: '0',
        pay: '0',
        lingxi: '1',
      },
      {
        func: '日程规则',
        free: '0',
        pay: '0',
        lingxi: '1',
      },
      {
        func: '会议室设定',
        free: '0',
        pay: '0',
        lingxi: '1',
      },
    ],
  },
  {
    pFunc: '任务',
    pFree: '0',
    pPay: '0',
    pLingx: '1',
    children: [
      {
        func: '任务邮件',
        free: '0',
        pay: '0',
        lingxi: '1',
      },
      {
        func: '邮件转稍后处理',
        free: '1',
        pay: '1',
        lingxi: '1',
      },
      {
        func: '手动建立待办',
        free: '1',
        pay: '1',
        lingxi: '1',
      },
    ],
  },
  {
    pFunc: '云文档',
    pFree: '1',
    pPay: '1',
    pLingx: '1',
    children: [
      {
        func: '协同文档/表格',
        free: '1',
        pay: '1',
        lingxi: '1',
      },
      {
        func: '导入/分享文件',
        free: '1',
        pay: '1',
        lingxi: '1',
      },
      {
        func: '存储空间',
        free: '1G/人-20G/企业',
        pay: '5G/人-50G/企业',
        lingxi: '5G/人-50G/企业',
      },
      {
        func: '在线资料包',
        free: '0',
        pay: '0',
        lingxi: '1',
      },
    ],
  },
  {
    pFunc: '企业文化',
    pFree: '0',
    pPay: '1',
    pLingx: '1',
    children: [
      {
        func: '企业域名',
        free: '1',
        pay: '1',
        lingxi: '1',
      },
      {
        func: '企业登录页/logo',
        free: '0',
        pay: '1',
        lingxi: '1',
      },
      {
        func: '企业动态签名',
        free: '0',
        pay: '0',
        lingxi: '1',
      },
      {
        func: '企业图片模板',
        free: '0',
        pay: '0',
        lingxi: '1',
      },
      {
        func: '移动端自定启动页',
        free: '0',
        pay: '0',
        lingxi: '1',
      },
    ],
  },
  {
    pFunc: '组织架构',
    pFree: '0',
    pPay: '1',
    pLingx: '1',
    children: [
      {
        func: '企业通讯录',
        free: '1',
        pay: '1',
        lingxi: '1',
      },
      {
        func: '个人通讯录',
        free: '1',
        pay: '1',
        lingxi: '1',
      },
      {
        func: '邮件列表',
        free: '0',
        pay: '1',
        lingxi: '1',
      },
    ],
  },
  {
    pFunc: '客户端安全管控',
    pFree: '0',
    pPay: '0',
    pLingx: '1',
    children: [
      {
        func: 'IP登录限制',
        free: '0',
        pay: '1',
        lingxi: '1',
      },
      {
        func: '强制修改密码',
        free: '0',
        pay: '1',
        lingxi: '1',
      },
      {
        func: '新设备登录提醒',
        free: '0',
        pay: '0',
        lingxi: '1',
      },
      {
        func: '通讯录外来信提醒',
        free: '0',
        pay: '0',
        lingxi: '1',
      },
      {
        func: '高级数据转移机制',
        free: '0',
        pay: '0',
        lingxi: '1',
      },
    ],
  },
  {
    pFunc: '超大参数',
    pFree: '0',
    pPay: '0',
    pLingx: '1',
    children: [
      {
        func: '超大存储',
        free: '0',
        pay: '100万封',
        lingxi: '200万封',
      },
      {
        func: '超大来信分类',
        free: '0',
        pay: '0',
        lingxi: '1',
      },
    ],
  },
  {
    pFunc: '服务与支持',
    pFree: '0',
    pPay: '0',
    pLingx: '1',
    children: [
      {
        func: '7*24小时服务',
        free: '0',
        pay: '1',
        lingxi: '1',
      },
      {
        func: '定期回访和业务回顾报告',
        free: '0',
        pay: '0',
        lingxi: '1',
      },
    ],
  },
];
