/* eslint-disable global-require */
/**
 * 世界各国国旗： https://flagpedia.asia/index
 * 业务系统国家与国旗映射表
 * 业务系统国家code与大数据国家code不一致，所以单独列一个业务系统国家与国旗的映射表
 * 缺少国旗：法罗群岛，（阿森松岛、特里斯坦达昆哈， 注意事项: 圣赫勒拿、阿森松和特里斯坦-达库尼亚 的官方国旗与 英国国旗 相同，但上述国旗使用频率更高）
 * 国旗可能不对：塞尔维亚
 *
 * 业务系统国家code与大数据国家code不一致,将同一个国家不一致的code都映射到同一个国旗图片上，以防后续后端修改以哪个为准时，前端找不到对应的国旗
 */
export default {
  Mexico: require('@/images/flags/Mexico.png'),
  'United States': require('@/images/flags/United_States.png'),
  'United States Minor Outlying Islands': require('@/images/flags/United_States.png'), // 增加国家，美属外岛，国旗同美国国旗
  Canada: require('@/images/flags/Canada.png'),
  Jamaica: require('@/images/flags/Jamaica.png'),
  Greenland: require('@/images/flags/Greenland.png'),
  Argentina: require('@/images/flags/Argentina.png'),
  Peru: require('@/images/flags/Peru.png'),
  'Costa Rica': require('@/images/flags/Costa_Rica.png'),
  Ecuador: require('@/images/flags/Ecuador.png'),
  Chile: require('@/images/flags/Chile.png'),
  Colombia: require('@/images/flags/Colombia.png'),
  Panama: require('@/images/flags/Panama.png'),
  Uruguay: require('@/images/flags/Uruguay.png'),
  Bolivia: require('@/images/flags/Bolivia.png'),
  Paraguay: require('@/images/flags/Paraguay.png'),
  Brazil: require('@/images/flags/Brazil.png'),
  Venezuela: require('@/images/flags/Venezuela.png'),
  Guatemala: require('@/images/flags/Guatemala.png'),
  Honduras: require('@/images/flags/Honduras.png'),
  'Dominican Republic': require('@/images/flags/Dominican.png'),
  'El Salvador': require('@/images/flags/El_Salvador.png'),
  Nicaragua: require('@/images/flags/Nicaragua.png'),
  Anguilla: require('@/images/flags/Anguilla.png'),
  Bermuda: require('@/images/flags/Bermuda.png'),
  Belize: require('@/images/flags/Belize.png'),
  Dominica: require('@/images/flags/Dominica.png'),
  Guyana: require('@/images/flags/Guyana.png'),
  'Virgin Islands,British': require('@/images/flags/British_Virgin_Islands.png'), // 和大数据不一致
  'Virgin Islands (British)': require('@/images/flags/British_Virgin_Islands.png'), // 保留大数据code
  'Cayman Islands': require('@/images/flags/Cayman_Islands.png'),
  Aruba: require('@/images/flags/Aruba.png'),
  Cuba: require('@/images/flags/Cuba.png'),
  'French Guiana': require('@/images/flags/French_Guiana.png'),
  Grenada: require('@/images/flags/Grenada.png'),
  'Antigua And Barbuda': require('@/images/flags/Antigua_and_Barbuda.png'),
  'Puerto Rico': require('@/images/flags/Puerto_Rico.png'),
  Suriname: require('@/images/flags/Surinam.png'),
  'Trinidad and Tobago': require('@/images/flags/Trinidad_and_Tobago.png'),
  'Virgin Islands': require('@/images/flags/Virgin_Islands.png'), // 和大数据不一致
  'Virgin Islands (U.S.)': require('@/images/flags/Virgin_Islands.png'), // 保留大数据code
  Martinique: require('@/images/flags/Martinique.png'),
  'St.Kitts and Nevis': require('@/images/flags/Saint_Kitts_and_Nevis.png'), // 和大数据不一致
  'Saint Kitts and Nevis': require('@/images/flags/Saint_Kitts_and_Nevis.png'), // 保留大数据code
  'St.Lucia': require('@/images/flags/Saint_Lucia.png'), // 和大数据不一致
  'Saint Lucia': require('@/images/flags/Saint_Lucia.png'), // 保留大数据code
  'St.Pierre and Miquelon': require('@/images/flags/Saint_Pierre_and_Miquelon.png'), // 和大数据不一致
  'St. Pierre and Miquelon': require('@/images/flags/Saint_Pierre_and_Miquelon.png'), // 保留大数据code
  'Netherlands Antilles': require('@/images/flags/Netherlands_Antilles.png'),
  'St.Vincent and the Grenadines': require('@/images/flags/Saint_Vincent_And_The_Grenadines.png'), // 和大数据不一致
  'Saint Vincent and the Grenadines': require('@/images/flags/Saint_Vincent_And_The_Grenadines.png'), // 保留大数据code
  Haiti: require('@/images/flags/Haiti.png'),
  'Turks and Caicos Islands': require('@/images/flags/Turks_and_Caicos_Islands.png'),
  Barbados: require('@/images/flags/Barbados.png'),
  Bahamas: require('@/images/flags/Bahamas.png'),
  Guadeloupe: require('@/images/flags/Guadeloupe.png'),
  Montserrat: require('@/images/flags/Montserrat.png'),
  India: require('@/images/flags/India.png'),
  Vietnam: require('@/images/flags/Vietnam.png'),
  Indonesia: require('@/images/flags/Indonesia.png'),
  Turkey: require('@/images/flags/Turkey.png'),
  Philippines: require('@/images/flags/Philippines.png'),
  Kazakhstan: require('@/images/flags/Kazakhstan.png'),
  'Sri Lanka': require('@/images/flags/Sri_Lanka.png'),
  Pakistan: require('@/images/flags/Pakistan.png'),
  Bangladesh: require('@/images/flags/Bengal.png'),
  Uzbekistan: require('@/images/flags/Uzbekistan.png'),
  China: require('@/images/flags/China.png'),
  Thailand: require('@/images/flags/Thailand.png'),
  'South Korea': require('@/images/flags/K.O.Korea.png'),
  Japan: require('@/images/flags/Japan.png'),
  Armenia: require('@/images/flags/Armenia.png'),
  'United Arab Emirates': require('@/images/flags/United_Arab_Emirates.png'),
  'Taiwan(China)': require('@/images/flags/China.png'),
  Malaysia: require('@/images/flags/Malaysia.png'),
  Singapore: require('@/images/flags/Singapore.png'),
  'Saudi Arabia': require('@/images/flags/Saudi_Arabia.png'),
  Kyrgyzstan: require('@/images/flags/Kyrgyzstan.png'),
  Tajikistan: require('@/images/flags/Tajikistan.png'),
  Iraq: require('@/images/flags/Iraq.png'),
  Mongolia: require('@/images/flags/Mongolia.png'),
  Kuwait: require('@/images/flags/Kuwait.png'),
  Iran: require('@/images/flags/Iran.png'),
  Azerbaijan: require('@/images/flags/Azerbaijan.png'),
  Qatar: require('@/images/flags/Qatar.png'),
  Georgia: require('@/images/flags/Georgia.png'),
  Turkmenistan: require('@/images/flags/Turkmenistan.png'),
  Oman: require('@/images/flags/Oman.png'),
  Bahrain: require('@/images/flags/Bahrain.png'),
  Israel: require('@/images/flags/Israel.png'),
  Cambodia: require('@/images/flags/Cambodia.png'),
  Myanmar: require('@/images/flags/Burma.png'),
  Afghanistan: require('@/images/flags/Afghanistan.png'),
  'Macau(China)': require('@/images/flags/Macao.png'),
  Macau: require('@/images/flags/Macao.png'),
  Jordan: require('@/images/flags/Jordan.png'),
  Lebanon: require('@/images/flags/Lebanon.png'),
  'Hong Kong(China)': require('@/images/flags/Hong_Kong.png'),
  'Hong Kong': require('@/images/flags/Hong_Kong.png'),
  Syria: require('@/images/flags/Syria.png'),
  Yemen: require('@/images/flags/Yemen.png'),
  Laos: require('@/images/flags/Laos.png'),
  'Palestinian Authority': require('@/images/flags/Palestine.png'), // 与大数据不一致
  Palestine: require('@/images/flags/Palestine.png'), // 保留大数据code
  Nepal: require('@/images/flags/Nepal.png'),
  Bhutan: require('@/images/flags/Bhutan.png'),
  Korea: require('@/images/flags/K.O.Korea.png'),
  'East Timor': require('@/images/flags/East_Timor.png'),
  'Brunei Darussalam': require('@/images/flags/Brunei.png'),
  Maldives: require('@/images/flags/Maldives.png'),
  Russia: require('@/images/flags/Russia.png'),
  Ukraine: require('@/images/flags/Ukraine.png'),
  'United Kingdom': require('@/images/flags/United_Kingdom.png'),
  'White Russia': require('@/images/flags/Belarus.png'), // 与大数据不一致
  Belarus: require('@/images/flags/Belarus.png'), // 保留大数据code
  Poland: require('@/images/flags/Poland.png'),
  Germany: require('@/images/flags/Germany.png'),
  Italy: require('@/images/flags/Italy.png'),
  Netherlands: require('@/images/flags/Netherlands.png'),
  Spain: require('@/images/flags/Spain.png'),
  Belgium: require('@/images/flags/Belgium.png'),
  France: require('@/images/flags/France.png'),
  Hungary: require('@/images/flags/Hungary.png'),
  'Czech Republic': require('@/images/flags/Czech_Republic.png'),
  Greece: require('@/images/flags/Greece.png'),
  Norway: require('@/images/flags/Norway.png'),
  Finland: require('@/images/flags/Finland.png'),
  Portugal: require('@/images/flags/Portugal.png'),
  Lithuania: require('@/images/flags/Lithuania.png'),
  Sweden: require('@/images/flags/Sweden.png'),
  Denmark: require('@/images/flags/Denmark.png'),
  Slovenia: require('@/images/flags/Slovene.png'),
  Latvia: require('@/images/flags/Latvia.png'),
  Austria: require('@/images/flags/Austria.png'),
  Slovakia: require('@/images/flags/Slovakia.png'),
  Estonia: require('@/images/flags/Estonia.png'),
  Malta: require('@/images/flags/Malta.png'),
  Romania: require('@/images/flags/Romania.png'),
  Switzerland: require('@/images/flags/Switzerland.png'),
  Serbia: require('@/images/flags/Serbia.png'), // 塞尔维亚 国旗可能有问题，暂不修改code:Serbia,Montenegro
  Ireland: require('@/images/flags/Ireland.png'),
  Bulgaria: require('@/images/flags/Bulgaria.png'),
  'Bosnia and Herzegovina': require('@/images/flags/Bosnia_and_Herzegovina.png'),
  Luxembourg: require('@/images/flags/Luxembourg.png'),
  Croatia: require('@/images/flags/Croatia.png'),
  'Macedonia,Former Yugoslav Republic of': require('@/images/flags/Macedonia.png'), // 和大数据不一致
  Macedonia: require('@/images/flags/Macedonia.png'), // 保留大数据code
  Liechtenstein: require('@/images/flags/Liechtenstein.png'),
  Cyprus: require('@/images/flags/Cyprus.png'),
  Montenegro: require('@/images/flags/Republic_of_Montenegro.png'),
  Albania: require('@/images/flags/Albania.png'),
  Iceland: require('@/images/flags/Iceland.png'),
  Guam: require('@/images/flags/Guam.png'),
  Andorra: require('@/images/flags/Andorra.png'),
  Gibraltar: require('@/images/flags/Gibraltar.png'),
  'Marshall Islands': require('@/images/flags/Marshall_Islands.png'),
  Monaco: require('@/images/flags/Monaco.png'),
  'San Marino': require('@/images/flags/San_Marino.png'),
  'VaticanCity State (Holy See)': require('@/images/flags/Vatican_City.png'),
  'Pitcairn Islands': require('@/images/flags/Pitcairn_Islands.png'), // 和大数据不一致
  Pitcairn: require('@/images/flags/Pitcairn_Islands.png'), // 保留大数据code
  'Republic of Kosovo': require('@/images/flags/Kosovo.png'),
  'Svalbard and Jan Mayen Islands': require('@/images/flags/Svalbard.png'),
  Guernsey: require('@/images/flags/Guernsey.png'),
  Namibia: require('@/images/flags/Namibia.png'),
  Uganda: require('@/images/flags/Uganda.png'),
  Nigeria: require('@/images/flags/Nigeria.png'),
  Botswana: require('@/images/flags/Botswana.png'),
  Ethiopia: require('@/images/flags/Ethiopia.png'),
  Kenya: require('@/images/flags/Kenya.png'),
  Ghana: require('@/images/flags/Ghana.png'),
  Lesotho: require('@/images/flags/Lesotho.png'),
  "Cote d'Ivoire": require('@/images/flags/Cote_DIvoire.png'),
  Zimbabwe: require('@/images/flags/Zimbabwe.png'),
  Cameroon: require('@/images/flags/Cameroon.png'),
  Egypt: require('@/images/flags/Egypt.png'),
  Liberia: require('@/images/flags/Liberia.png'),
  Chad: require('@/images/flags/Chad.png'),
  Algeria: require('@/images/flags/Algeria.png'),
  Djibouti: require('@/images/flags/Djibouti.png'),
  'Central African Republic': require('@/images/flags/Central_African.png'),
  Morocco: require('@/images/flags/Morocco.png'),
  'South Africa': require('@/images/flags/South_Africa.png'),
  Sudan: require('@/images/flags/Sudan.png'),
  Tunisia: require('@/images/flags/Tunisia.png'),
  Tanzania: require('@/images/flags/Tanzania.png'),
  Senegal: require('@/images/flags/Senegal.png'),
  Benin: require('@/images/flags/Benin.png'),
  Togo: require('@/images/flags/Togo.png'),
  Libya: require('@/images/flags/Libya.png'),
  Seychelles: require('@/images/flags/Seychelles.png'),
  Angola: require('@/images/flags/Angola.png'),
  Mali: require('@/images/flags/Mali.png'),
  Rwanda: require('@/images/flags/Rwanda.png'),
  'Western Sahara': require('@/images/flags/Western_Sahara.png'),
  Reunion: require('@/images/flags/Reunion.png'),
  'Sierra Leone': require('@/images/flags/Sierra_Leone.png'),
  Burundi: require('@/images/flags/Burundi.png'),
  'Burkina Faso': require('@/images/flags/BurkinaFaso.png'),
  'Cape Verde': require('@/images/flags/Cape_Verde_Is..png'),
  Comoros: require('@/images/flags/Comoros.png'),
  'Congo(DRC)': require('@/images/flags/The_Democratic_Republic_of_the_Congo.png'), // 和大数据不一致
  'Congo, the Democratic Republic of the': require('@/images/flags/The_Democratic_Republic_of_the_Congo.png'), // 保留大数据code
  'Equatorial Guinea': require('@/images/flags/Equatorial_Guinea.png'),
  Gabon: require('@/images/flags/Gabon.png'),
  Guinea: require('@/images/flags/Guinea.png'),
  Gambia: require('@/images/flags/Gambia.png'),
  Kiribati: require('@/images/flags/Kiribati.png'),
  Madagascar: require('@/images/flags/Madagascar.png'),
  Malawi: require('@/images/flags/Malawi.png'),
  Mauritania: require('@/images/flags/Mauritania.png'),
  Mauritius: require('@/images/flags/Mauritius.png'),
  Mozambique: require('@/images/flags/Mozambique.png'),
  Niger: require('@/images/flags/Niger.png'),
  'Solomon Islands': require('@/images/flags/Solomon_Islands.png'),
  Somalia: require('@/images/flags/Somalia.png'),
  Swaziland: require('@/images/flags/Swaziland.png'),
  Zambia: require('@/images/flags/Zambia.png'),
  Mayotte: require('@/images/flags/Mayotte.png'),
  'Bouvet Island': require('@/images/flags/Bouvet_Island.png'),
  Eritrea: require('@/images/flags/Eritrea.png'),
  'Sao Tome and Principe': require('@/images/flags/Sao_Tome_and_Principe.png'),
  Congo: require('@/images/flags/The_Republic_of_Congo.png'), // 和大数据不一致
  'St.Helena': require('@/images/flags/Saint_Helena.png'), // 和大数据不一致
  'Saint Helena': require('@/images/flags/Saint_Helena.png'), // 保留大数据code
  'Guinea-Bissau': require('@/images/flags/Guinea-Bissau.png'),
  Australia: require('@/images/flags/Australia.png'),
  'Fiji Islands': require('@/images/flags/Fiji.png'), // 和大数据不一致
  Fiji: require('@/images/flags/Fiji.png'), // 保留大数据code
  'New Zealand': require('@/images/flags/New_Zealand.png'),
  'American Samoa': require('@/images/flags/American_Samoa.png'),
  'Frech Polynesia': require('@/images/flags/French_Polynesia.png'), // 和大数据不一致
  'French Polynesia': require('@/images/flags/French_Polynesia.png'), // 保留大数据code
  'Christmas Island': require('@/images/flags/Christmas_Island.png'),
  'Cook Islands': require('@/images/flags/Cook_Islands.png'),
  Nauru: require('@/images/flags/Nauru.png'),
  Micronesia: require('@/images/flags/Micronesia.png'), // 与大数据不一致
  'Micronesia, Federated States of': require('@/images/flags/Micronesia.png'), // 保留大数据code
  'New Caledonia': require('@/images/flags/New_Caledonia.png'),
  Niue: require('@/images/flags/Niue.png'),
  Palau: require('@/images/flags/Palau.png'),
  'Papua New Guinea': require('@/images/flags/Papua_New_Guinea.png'),
  Tokelau: require('@/images/flags/Tokelau.png'),
  Tonga: require('@/images/flags/Tonga.png'),
  Tuvalu: require('@/images/flags/Tuvalu.png'),
  Vanuatu: require('@/images/flags/Vanuatu.png'),
  'Northern Mariana Islands': require('@/images/flags/Northern_Mariana_Islands.png'),
  'Wallis and Futuna Islands': require('@/images/flags/Wallis_And_Futuna_Islands.png'),
  'Norfolk Island': require('@/images/flags/Norfolk_Island.png'),
  'South Georgia and South Sandwich Islands': require('@/images/flags/South_Georgia_and_the_South_Sandwich_Islands.png'), // 与大数据不一致
  'South Georgia and the South Sandwich Islands': require('@/images/flags/South_Georgia_and_the_South_Sandwich_Islands.png'), // 保留大数据code
  'Falkland Islands (Malvinas)': require('@/images/flags/South_Georgia_and_the_South_Sandwich_Islands.png'), // 保留大数据code
  'Aland lslands': require('@/images/flags/Aland_Islands.png'), // 与大数据不一致
  'Aland Islands': require('@/images/flags/Aland_Islands.png'), // 保留大数据code
  Antarctica: require('@/images/flags/Antarctica.png'),
  Brunei: require('@/images/flags/Brunei.png'),
  'Antigua and Barbuda': require('@/images/flags/Antigua_and_Barbuda.png'),
  'North Korea': require('@/images/flags/D.P.R.Korea.png'),
  'Timor-Leste': require('@/images/flags/East_Timor.png'),
  Taiwan: require('@/images/flags/China.png'),
  Samoa: require('@/images/flags/American_Samoa.png'),
  'Wallis and Futuna': require('@/images/flags/Wallis_And_Futuna_Islands.png'),
  'Svalbard and Jan Mayen': require('@/images/flags/Svalbard.png'),
  'European Union': require('@/images/flags/European_Union.png'),
  Moldova: require('@/images/flags/Moldova.png'), // 和大数据不一致
  'Moldova, Republic of': require('@/images/flags/Moldova.png'), // 保留大数据code
  'The Republic of Moldova': require('@/images/flags/Moldova.png'), // 保留大数据code
  'Northern Ireland': require('@/images/flags/Ireland.png'),
  Wales: require('@/images/flags/Wales.png'),
  KosovoCzech: require('@/images/flags/Kosovo.png'),
  Czech: require('@/images/flags/Czech_Republic.png'),
  Eswatini: require('@/images/flags/Swaziland.png'),
  "Cote D'Ivoire": require('@/images/flags/Cote_DIvoire.png'),
  'Saint Barthélemy': require('@/images/flags/Saint_Barthelemy.png'),
  'Saint Pierre and Miquelon': require('@/images/flags/Saint_Pierre_and_Miquelon.png'),
  'United States Virgin Islands': require('@/images/flags/Virgin_Islands.png'),
  'French Southern and Antarctic Lands': require('@/images/flags/French_Southern_Territories.png'), // 和大数据不一致
  'French Southern Territories': require('@/images/flags/French_Southern_Territories.png'), // 保留大数据code
  'Cocos(Keeling)Islands': require('@/images/flags/Cocos_Islands.png'), // 和大数据不一致
  'Cocos (Keeling) Islands': require('@/images/flags/Cocos_Islands.png'), // 保留大数据code
  Curaçao: require('@/images/flags/Curacao.png'),
  'Falkland Islands': require('@/images/flags/South_Georgia_and_the_South_Sandwich_Islands.png'), // 和大数据不一致
  'Caribbean Netherlands': require('@/images/flags/Caribbean_Netherlands.png'),
  'Sint Maarten (Dutch part)': require('@/images/flags/Sint_Maarten.png'),
  'Heard Island and McDonald Islands': require('@/images/flags/Heard_Island_and_McDonald_Islands.png'),
  Kosovo: require('@/images/flags/Kosovo.png'),
  'Isle of Man': require('@/images/flags/Isle_of_Man.png'),
  'Saint Martin (French part)': require('@/images/flags/Saint_Martin.png'),
  Czechoslovakia: require('@/images/flags/Czechoslovakia.png'),
  Scotland: require('@/images/flags/Scotland.png'),
  'British Indian Ocean Territory': require('@/images/flags/British_Indian_Ocean_Territory.png'),
  Jersey: require('@/images/flags/Jersey.png'),
  'Vatican City': require('@/images/flags/Vatican_City.png'),
};
