FROM centos/nodejs-12-centos7
USER root
WORKDIR /home/root
ENV VER 2.16.5
RUN npm install --global yarn
RUN yarn config set cache-folder /cache && yarn config set registry https://registry.npm.taobao.org/
#RUN yum -y remove git*
#COPY v${VER}.tar.gz /home/root
#RUN tar -xvf v${VER}.tar.gz && rm -f v${VER}.tar.gz && cd git-* && make configure &&  ./configure --prefix=/usr &&  make &&  make install


