export interface MenuPermissionTypes {
  EDM_SENDBOX: boolean;
  EDM_DRAFT_LIST: boolean;
  EDM_DATA_STAT: boolean;
  EDM_BLACKLIST: boolean;
  EDM_TEMPLATE: boolean;
  EDM: boolean;
  ADDRESS_BOOK_LIST: boolean;
  ADDRESS_OPEN_SEA: boolean;
  MARKET_DATA_STAT: boolean;
  ADDRESS_BOOK: boolean;
  WHATSAPP_SEND_TASK: boolean;
  WHATSAPP_DATA_STAT: boolean;
  WHATSAPP_MSG: boolean;
  WHATSAPP_MSG_TPL_SETTING: boolean;
  WHATSAPP_PERSONAL_MSG: boolean;
  WHATSAPP_PERSONAL_SEND_TASK: boolean;
  WHATSAPP: boolean;
  FACEBOOK_MY_MAIN_PAGE: boolean;
  FACEBOOK_MY_POST: boolean;
  FACEBOOK_MSG: boolean;
  FACEBOOK: boolean;
  /** 线索列表 */
  CONTACT_CHANNEL_LIST: boolean;
  /** 客户列表 */
  CONTACT_LIST: boolean;
  /** 商机列表 */
  CONTACT_COMMERCIAL_LIST: boolean;
  CONTACT_TAG_MANAGE: boolean;
  /** 线索公海 */
  CHANNEL_OPEN_SEA: boolean;
  BROWSER_EXTENSION: boolean;
  /** 客户公海 */
  CONTACT_OPEN_SEA: boolean;
  CONTACT_DATA_MIGRATION: boolean;
  CONTACT: boolean;
  /** 订单 */
  ORDER: boolean;
  /** 本地商品 */
  LOCAL_PRODUCT: boolean;
  /** 平台商品 */
  PLATFORM_PRODUCT: boolean;
  /** 供应商管理 */
  SUPPLIER_MANAGE: boolean;
  /** 推荐列表 */
  CUSTOMER_RECOMMEND: boolean;
  PRODUCT: boolean;
  WORKBENCH: boolean;
  CUSTOMS: boolean;
  PRIVILEGE: boolean;
  ORG_SETTINGS_FIELD_SETTING: boolean;
  ORG_SETTINGS_SALES_STAGE_SETTING: boolean;
  ORG_SETTINGS_TMPL_VARIABLE_SETTING: boolean;
  ORG_SETTINGS_QUOTA_SETTING: boolean;
  ORG_SETTINGS_AI_TAG_SETTING: boolean;
  ORG_SETTINGS_DUPLICATE_CHECK_SETTING: boolean;
  ORG_SETTINGS_PEER_SETTING: boolean;
  ORG_SETTINGS_OPEN_SEA_SETTING: boolean;
  ORG_SETTINGS_NOTIFY_SETTING: boolean;
  ORG_SETTINGS_WHITELIST_SETTING: boolean;
  ORG_SETTINGS_WORD_ART_LIBRARY: boolean;
  ORG_SETTINGS_TASK_CENTER_RULE_SETTING: boolean;
  ORG_SETTINGS: boolean;
  GLOBAL_SEARCH: boolean;
  PREVIOUS_CONTACT_AUTO_RECOMMEND: boolean;
  PREVIOUS_CONTACT_CUSTOM_RECOMMEND: boolean;
  PREVIOUS_CONTACT_OP_LIST: boolean;
  PREVIOUS_CONTACT_GRANT_ADMIN: boolean;
  PREVIOUS_CONTACT: boolean;
  WEBSITE_ADMIN_MINE: boolean;
  WEBSITE_ADMIN_DATA: boolean;
  WEBSITE_ADMIN_MARKET: boolean;
  WEBSITE_TARGET_CONTACT: boolean;
  WEBSITE_ADMIN: boolean;
  TASK_CENTER: boolean;
}

export const devDefaultMenuPermission: MenuPermissionTypes = {
  EDM_SENDBOX: true,
  EDM_DRAFT_LIST: true,
  EDM_DATA_STAT: true,
  EDM_BLACKLIST: true,
  EDM_TEMPLATE: true,
  EDM: true,
  ADDRESS_BOOK_LIST: true,
  ADDRESS_OPEN_SEA: true,
  MARKET_DATA_STAT: true,
  ADDRESS_BOOK: true,
  WHATSAPP_SEND_TASK: true,
  WHATSAPP_DATA_STAT: true,
  WHATSAPP_MSG: true,
  WHATSAPP_MSG_TPL_SETTING: true,
  WHATSAPP_PERSONAL_MSG: true,
  WHATSAPP_PERSONAL_SEND_TASK: true,
  WHATSAPP: true,
  FACEBOOK_MY_MAIN_PAGE: true,
  FACEBOOK_MY_POST: true,
  FACEBOOK_MSG: true,
  FACEBOOK: true,
  CONTACT_CHANNEL_LIST: true,
  CONTACT_LIST: true,
  CONTACT_COMMERCIAL_LIST: true,
  CONTACT_TAG_MANAGE: true,
  CHANNEL_OPEN_SEA: true,
  BROWSER_EXTENSION: true,
  CONTACT_OPEN_SEA: true,
  CONTACT_DATA_MIGRATION: true,
  CONTACT: true,
  ORDER: true,
  LOCAL_PRODUCT: true,
  PLATFORM_PRODUCT: true,
  SUPPLIER_MANAGE: true,
  CUSTOMER_RECOMMEND: true,
  PRODUCT: true,
  WORKBENCH: true,
  CUSTOMS: true,
  PRIVILEGE: true,
  ORG_SETTINGS_FIELD_SETTING: true,
  ORG_SETTINGS_SALES_STAGE_SETTING: true,
  ORG_SETTINGS_TMPL_VARIABLE_SETTING: true,
  ORG_SETTINGS_QUOTA_SETTING: true,
  ORG_SETTINGS_AI_TAG_SETTING: true,
  ORG_SETTINGS_DUPLICATE_CHECK_SETTING: true,
  ORG_SETTINGS_PEER_SETTING: true,
  ORG_SETTINGS_OPEN_SEA_SETTING: true,
  ORG_SETTINGS_NOTIFY_SETTING: true,
  ORG_SETTINGS_WHITELIST_SETTING: true,
  ORG_SETTINGS_WORD_ART_LIBRARY: true,
  ORG_SETTINGS_TASK_CENTER_RULE_SETTING: true,
  ORG_SETTINGS: true,
  GLOBAL_SEARCH: true,
  PREVIOUS_CONTACT_AUTO_RECOMMEND: true,
  PREVIOUS_CONTACT_CUSTOM_RECOMMEND: true,
  PREVIOUS_CONTACT_OP_LIST: true,
  PREVIOUS_CONTACT_GRANT_ADMIN: true,
  PREVIOUS_CONTACT: true,
  WEBSITE_ADMIN_MINE: true,
  WEBSITE_ADMIN_DATA: true,
  WEBSITE_ADMIN_MARKET: true,
  WEBSITE_TARGET_CONTACT: true,
  WEBSITE_ADMIN: true,
  TASK_CENTER: true,
};
