export const permissionMockData = {
  EDM: {
    resourceLabel: 'EDM',
    resourceName: '邮件营销',
    dataPrivilege: {
      accessId: '4',
      accessLabel: 'DATA',
      accessName: '数据权限',
      accessType: 'DATA',
      accessRange: null,
    },
    funcPrivileges: [
      {
        accessId: '2',
        accessLabel: 'OP',
        accessName: '操作权限',
        accessType: 'FUNC',
        accessRange: null,
      },
      {
        accessId: '3',
        accessLabel: 'VIEW',
        accessName: '查看权限',
        accessType: 'FUNC',
        accessRange: null,
      },
      {
        accessId: '5',
        accessLabel: 'DELETE',
        accessName: '删除权限',
        accessType: 'FUNC',
        accessRange: null,
      },
    ],
  },
  CONTACT: {
    resourceLabel: 'CONTACT',
    resourceName: '客户列表',
    dataPrivilege: {
      accessId: '4',
      accessLabel: 'DATA',
      accessName: '数据权限',
      accessType: 'DATA',
      accessRange: null,
    },
    funcPrivileges: [
      {
        accessId: '2',
        accessLabel: 'OP',
        accessName: '操作权限',
        accessType: 'FUNC',
        accessRange: null,
      },
      {
        accessId: '3',
        accessLabel: 'VIEW',
        accessName: '查看权限',
        accessType: 'FUNC',
        accessRange: null,
      },
      {
        accessId: '5',
        accessLabel: 'DELETE',
        accessName: '删除权限',
        accessType: 'FUNC',
        accessRange: null,
      },
      {
        accessId: '16',
        accessLabel: 'EXPORT',
        accessName: '导出',
        accessType: 'FUNC',
        accessRange: null,
      },
    ],
  },
  COMMERCIAL: {
    resourceLabel: 'COMMERCIAL',
    resourceName: '商机',
    dataPrivilege: {
      accessId: '4',
      accessLabel: 'DATA',
      accessName: '数据权限',
      accessType: 'DATA',
      accessRange: null,
    },
    funcPrivileges: [
      {
        accessId: '2',
        accessLabel: 'OP',
        accessName: '操作权限',
        accessType: 'FUNC',
        accessRange: null,
      },
      {
        accessId: '3',
        accessLabel: 'VIEW',
        accessName: '查看权限',
        accessType: 'FUNC',
        accessRange: null,
      },
      {
        accessId: '5',
        accessLabel: 'DELETE',
        accessName: '删除权限',
        accessType: 'FUNC',
        accessRange: null,
      },
      {
        accessId: '16',
        accessLabel: 'EXPORT',
        accessName: '导出',
        accessType: 'FUNC',
        accessRange: null,
      },
    ],
  },
  CHANNEL: {
    resourceLabel: 'CHANNEL',
    resourceName: '线索列表',
    dataPrivilege: {
      accessId: '4',
      accessLabel: 'DATA',
      accessName: '数据权限',
      accessType: 'DATA',
      accessRange: null,
    },
    funcPrivileges: [
      {
        accessId: '2',
        accessLabel: 'OP',
        accessName: '操作权限',
        accessType: 'FUNC',
        accessRange: null,
      },
      {
        accessId: '3',
        accessLabel: 'VIEW',
        accessName: '查看权限',
        accessType: 'FUNC',
        accessRange: null,
      },
      {
        accessId: '5',
        accessLabel: 'DELETE',
        accessName: '删除权限',
        accessType: 'FUNC',
        accessRange: null,
      },
      {
        accessId: '16',
        accessLabel: 'EXPORT',
        accessName: '导出',
        accessType: 'FUNC',
        accessRange: null,
      },
      {
        accessId: '17',
        accessLabel: 'FORCE_DELETE',
        accessName: '强制删除',
        accessType: 'FUNC',
        accessRange: null,
      },
    ],
  },
  CHANNEL_OPEN_SEA: {
    resourceLabel: 'CHANNEL_OPEN_SEA',
    resourceName: '公海线索',
    funcPrivileges: [
      // {
      //     accessId: '2',
      //     accessLabel: 'OP',
      //     accessName: '操作权限',
      //     accessType: 'FUNC',
      //     accessRange: null,
      // },
      {
        accessId: '3',
        accessLabel: 'VIEW',
        accessName: '查看权限',
        accessType: 'FUNC',
        accessRange: null,
      },
      // {
      //     accessId: '5',
      //     accessLabel: 'DELETE',
      //     accessName: '删除权限',
      //     accessType: 'FUNC',
      //     accessRange: null,
      // },
      {
        accessId: '6',
        accessLabel: 'CLAIM',
        accessName: '认领权限',
        accessType: 'FUNC',
        accessRange: null,
      },
      {
        accessId: '7',
        accessLabel: 'ALLOT',
        accessName: '分配权限',
        accessType: 'FUNC',
        accessRange: null,
      },
      {
        accessId: '35',
        accessLabel: 'IMPORT',
        accessName: '导入',
        accessType: 'FUNC',
        accessRange: null,
      },
    ],
  },
  WORKBENCH: {
    resourceLabel: 'WORKBENCH',
    resourceName: '工作台',
    funcPrivileges: [
      {
        accessId: '8',
        accessLabel: 'VIEW_MY_CONTACT_EMAIL',
        accessName: '查看我的客户邮件',
        accessType: 'FUNC',
        accessRange: null,
      },
      {
        accessId: '9',
        accessLabel: 'VIEW_MY_EDM_EMAIL',
        accessName: '查看我的邮件营销',
        accessType: 'FUNC',
        accessRange: null,
      },
      {
        accessId: '10',
        accessLabel: 'VIEW_ALL_EDM_EMAIL',
        accessName: '查看全部邮件营销',
        accessType: 'FUNC',
        accessRange: null,
      },
      {
        accessId: '11',
        accessLabel: 'VIEW_RECENTLY_SCHEDULE',
        accessName: '查看最近日程',
        accessType: 'FUNC',
        accessRange: null,
      },
      {
        accessId: '12',
        accessLabel: 'VIEW_MY_CONTACT_BOARD',
        accessName: '查看我的客户看板',
        accessType: 'FUNC',
        accessRange: null,
      },
      {
        accessId: '32',
        accessLabel: 'VIEW_STAFF_PK_LIST',
        accessName: '查看员工PK榜',
        accessType: 'FUNC',
        accessRange: null,
      },
      {
        accessId: '15',
        accessLabel: 'VIEW_ALL_CONTACT_STATE',
        accessName: '查看全部客户动态',
        accessType: 'FUNC',
        accessRange: null,
      },
      {
        accessId: '14',
        accessLabel: 'VIEW_MY_CONTACT_STATE',
        accessName: '查看我的客户动态',
        accessType: 'FUNC',
        accessRange: null,
      },
      {
        accessId: '13',
        accessLabel: 'VIEW_ALL_CONTACT_BOARD',
        accessName: '查看全部客户看板',
        accessType: 'FUNC',
        accessRange: null,
      },
    ],
  },
  CUSTOMS: {
    resourceLabel: 'CUSTOMS',
    resourceName: '海关数据',
    funcPrivileges: [
      {
        accessId: '3',
        accessLabel: 'VIEW',
        accessName: '查看权限',
        accessType: 'FUNC',
        accessRange: null,
      },
    ],
  },
  WHATSAPP: {
    resourceLabel: 'WHATSAPP',
    resourceName: 'whatsapp营销',
    dataPrivilege: {
      accessId: '4',
      accessLabel: 'DATA',
      accessName: '数据权限',
      accessType: 'DATA',
      accessRange: null,
    },
    funcPrivileges: [
      {
        accessId: '2',
        accessLabel: 'OP',
        accessName: '操作权限',
        accessType: 'FUNC',
        accessRange: null,
      },
      {
        accessId: '3',
        accessLabel: 'VIEW',
        accessName: '查看权限',
        accessType: 'FUNC',
        accessRange: null,
      },
      {
        accessId: '5',
        accessLabel: 'DELETE',
        accessName: '删除权限',
        accessType: 'FUNC',
        accessRange: null,
      },
    ],
  },
  GLOBAL_SEARCH: {
    resourceLabel: 'GLOBAL_SEARCH',
    resourceName: '全球搜索',
    funcPrivileges: [
      {
        accessId: '3',
        accessLabel: 'VIEW',
        accessName: '查看权限',
        accessType: 'FUNC',
        accessRange: null,
      },
    ],
  },
  ORG_SETTINGS: {
    resourceLabel: 'ORG_SETTINGS',
    resourceName: '企业设置',
    funcPrivileges: [
      {
        accessId: '20',
        accessLabel: 'EDM_TMPL_VARIABLE_SETTING',
        accessName: '邮件营销模版变量',
        accessType: 'FUNC',
        accessRange: null,
      },
      {
        accessId: '21',
        accessLabel: 'EDM_QUOTA_SETTING',
        accessName: '邮件营销配额',
        accessType: 'FUNC',
        accessRange: null,
      },
      {
        accessId: '33',
        accessLabel: 'TASK_CENTER_RULE_SETTING',
        accessName: '任务规则设置',
        accessType: 'FUNC',
        accessRange: null,
      },
      {
        accessId: '22',
        accessLabel: 'CONTACT_AI_TAG_SETTING',
        accessName: '邮件智能标签',
        accessType: 'FUNC',
        accessRange: null,
      },
      {
        accessId: '24',
        accessLabel: 'WHATSAPP_PEER_SETTING',
        accessName: 'WhatsApp对接',
        accessType: 'FUNC',
        accessRange: null,
      },
      {
        accessId: '29',
        accessLabel: 'NOTIFY_SETTING',
        accessName: '通知设置',
        accessType: 'FUNC',
        accessRange: null,
      },
      {
        accessId: '30',
        accessLabel: 'PREVIOUS_CONTACT_WHITELIST_SETTING',
        accessName: '往来邮件-授权白名单',
        accessType: 'FUNC',
        accessRange: null,
      },
      {
        accessId: '18',
        accessLabel: 'CONTACT_FIELD_SETTING',
        accessName: '字段设置',
        accessType: 'FUNC',
        accessRange: null,
      },
      {
        accessId: '19',
        accessLabel: 'CONTACT_SALES_STAGE_SETTING',
        accessName: '销售阶段设置',
        accessType: 'FUNC',
        accessRange: null,
      },
      {
        accessId: '23',
        accessLabel: 'CONTACT_DUPLICATE_CHECK_SETTING',
        accessName: '字段查重',
        accessType: 'FUNC',
        accessRange: null,
      },
    ],
  },
  PREVIOUS_CONTACT: {
    resourceLabel: 'PREVIOUS_CONTACT',
    resourceName: '往来邮件筛选',
    funcPrivileges: [
      {
        accessId: '25',
        accessLabel: 'CONTACT_GRANT_EMAIL_SETTING',
        accessName: '授权管理',
        accessType: 'FUNC',
        accessRange: null,
      },
      {
        accessId: '26',
        accessLabel: 'AUTO_RECOMMEND',
        accessName: '自动筛选',
        accessType: 'FUNC',
        accessRange: null,
      },
      {
        accessId: '27',
        accessLabel: 'CUSTOM_RECOMMEND',
        accessName: '手动筛选',
        accessType: 'FUNC',
        accessRange: null,
      },
    ],
  },
  CONTACT_OPEN_SEA: {
    resourceLabel: 'CONTACT_OPEN_SEA',
    resourceName: '客户公海',
    funcPrivileges: [
      {
        accessId: '3',
        accessLabel: 'VIEW',
        accessName: '查看权限',
        accessType: 'FUNC',
        accessRange: null,
      },
      {
        accessId: '5',
        accessLabel: 'DELETE',
        accessName: '删除权限',
        accessType: 'FUNC',
        accessRange: null,
      },
      {
        accessId: '6',
        accessLabel: 'CLAIM',
        accessName: '认领权限',
        accessType: 'FUNC',
        accessRange: null,
      },
      {
        accessId: '7',
        accessLabel: 'ALLOT',
        accessName: '分配权限',
        accessType: 'FUNC',
        accessRange: null,
      },
      {
        accessId: '35',
        accessLabel: 'IMPORT',
        accessName: '导入',
        accessType: 'FUNC',
        accessRange: null,
      },
    ],
  },
  CONTACT_EMAIL: {
    resourceLabel: 'CONTACT_EMAIL',
    resourceName: '客户邮件',
    funcPrivileges: [
      {
        accessId: '3',
        accessLabel: 'VIEW',
        accessName: '查看权限',
        accessType: 'FUNC',
        accessRange: null,
      },
    ],
  },
  COLLEAGUE_EMAIL: {
    resourceLabel: 'COLLEAGUE_EMAIL',
    resourceName: '下属邮件',
    dataPrivilege: {
      accessId: '4',
      accessLabel: 'DATA',
      accessName: '数据权限',
      accessType: 'DATA',
      accessRange: null,
    },
    funcPrivileges: [
      {
        accessId: '3',
        accessLabel: 'VIEW',
        accessName: '查看权限',
        accessType: 'FUNC',
        accessRange: null,
      },
    ],
  },
  ADDRESS_BOOK: {
    resourceLabel: 'ADDRESS_BOOK',
    resourceName: '营销联系人',
    funcPrivileges: [
      {
        accessId: '16',
        accessLabel: 'EXPORT',
        accessName: '导出',
        accessType: 'FUNC',
        accessRange: null,
      },
      {
        accessId: '2',
        accessLabel: 'OP',
        accessName: '操作权限',
        accessType: 'FUNC',
        accessRange: null,
      },
      {
        accessId: '3',
        accessLabel: 'VIEW',
        accessName: '查看权限',
        accessType: 'FUNC',
        accessRange: null,
      },
      {
        accessId: '5',
        accessLabel: 'DELETE',
        accessName: '删除权限',
        accessType: 'FUNC',
        accessRange: null,
      },
    ],
  },
  ADDRESS_OPEN_SEA: {
    resourceLabel: 'ADDRESS_OPEN_SEA',
    resourceName: '地址簿公海',
    funcPrivileges: [
      {
        accessId: '16',
        accessLabel: 'EXPORT',
        accessName: '导出',
        accessType: 'FUNC',
        accessRange: null,
      },
      {
        accessId: '2',
        accessLabel: 'OP',
        accessName: '操作权限',
        accessType: 'FUNC',
        accessRange: null,
      },
      {
        accessId: '3',
        accessLabel: 'VIEW',
        accessName: '查看权限',
        accessType: 'FUNC',
        accessRange: null,
      },
      {
        accessId: '5',
        accessLabel: 'DELETE',
        accessName: '删除权限',
        accessType: 'FUNC',
        accessRange: null,
      },
      {
        accessId: '7',
        accessLabel: 'ALLOT',
        accessName: '分配权限',
        accessType: 'FUNC',
        accessRange: null,
      },
    ],
  },
  FACEBOOK: {
    resourceLabel: 'FACEBOOK',
    resourceName: 'Facebook营销',
    dataPrivilege: {
      accessId: '4',
      accessLabel: 'DATA',
      accessName: '数据权限',
      accessType: 'DATA',
      accessRange: null,
    },
    funcPrivileges: [
      {
        accessId: '2',
        accessLabel: 'OP',
        accessName: '操作权限',
        accessType: 'FUNC',
        accessRange: null,
      },
      {
        accessId: '3',
        accessLabel: 'VIEW',
        accessName: '查看权限',
        accessType: 'FUNC',
        accessRange: null,
      },
    ],
  },
  FACEBOOK_ACCOUNT: {
    resourceLabel: 'FACEBOOK_ACCOUNT',
    resourceName: 'Facebook账号管理',
    dataPrivilege: {
      accessId: '4',
      accessLabel: 'DATA',
      accessName: '数据权限',
      accessType: 'DATA',
      accessRange: null,
    },
    funcPrivileges: [
      {
        accessId: '31',
        accessLabel: 'UNBIND',
        accessName: '解绑权限',
        accessType: 'FUNC',
        accessRange: null,
      },
    ],
  },
  ORDER: {
    resourceLabel: 'ORDER',
    resourceName: '销售订单',
    dataPrivilege: {
      accessId: '4',
      accessLabel: 'DATA',
      accessName: '数据权限',
      accessType: 'DATA',
      accessRange: null,
    },
    funcPrivileges: [
      {
        accessId: '2',
        accessLabel: 'OP',
        accessName: '操作权限',
        accessType: 'FUNC',
        accessRange: null,
      },
      {
        accessId: '3',
        accessLabel: 'VIEW',
        accessName: '查看权限',
        accessType: 'FUNC',
        accessRange: null,
      },
      {
        accessId: '5',
        accessLabel: 'DELETE',
        accessName: '删除权限',
        accessType: 'FUNC',
        accessRange: null,
      },
      {
        accessId: '16',
        accessLabel: 'EXPORT',
        accessName: '导出',
        accessType: 'FUNC',
        accessRange: null,
      },
    ],
  },
  LOCAL_PRODUCT: {
    resourceLabel: 'LOCAL_PRODUCT',
    resourceName: '本地商品',
    dataPrivilege: {
      accessId: '4',
      accessLabel: 'DATA',
      accessName: '数据权限',
      accessType: 'DATA',
      accessRange: null,
    },
    funcPrivileges: [
      {
        accessId: '2',
        accessLabel: 'OP',
        accessName: '操作权限',
        accessType: 'FUNC',
        accessRange: null,
      },
      {
        accessId: '3',
        accessLabel: 'VIEW',
        accessName: '查看权限',
        accessType: 'FUNC',
        accessRange: null,
      },
      {
        accessId: '5',
        accessLabel: 'DELETE',
        accessName: '删除权限',
        accessType: 'FUNC',
        accessRange: null,
      },
      {
        accessId: '16',
        accessLabel: 'EXPORT',
        accessName: '导出',
        accessType: 'FUNC',
        accessRange: null,
      },
    ],
  },
  PLATFORM_PRODUCT: {
    resourceLabel: 'PLATFORM_PRODUCT',
    resourceName: '平台商品',
    dataPrivilege: {
      accessId: '4',
      accessLabel: 'DATA',
      accessName: '数据权限',
      accessType: 'DATA',
      accessRange: null,
    },
    funcPrivileges: [
      {
        accessId: '2',
        accessLabel: 'OP',
        accessName: '操作权限',
        accessType: 'FUNC',
        accessRange: null,
      },
      {
        accessId: '3',
        accessLabel: 'VIEW',
        accessName: '查看权限',
        accessType: 'FUNC',
        accessRange: null,
      },
      {
        accessId: '5',
        accessLabel: 'DELETE',
        accessName: '删除权限',
        accessType: 'FUNC',
        accessRange: null,
      },
    ],
  },
  SUPPLIER_MANAGER: {
    resourceLabel: 'SUPPLIER_MANAGER',
    resourceName: '供应商',
    dataPrivilege: {
      accessId: '4',
      accessLabel: 'DATA',
      accessName: '数据权限',
      accessType: 'DATA',
      accessRange: null,
    },
    funcPrivileges: [
      {
        accessId: '2',
        accessLabel: 'OP',
        accessName: '操作权限',
        accessType: 'FUNC',
        accessRange: null,
      },
      {
        accessId: '3',
        accessLabel: 'VIEW',
        accessName: '查看权限',
        accessType: 'FUNC',
        accessRange: null,
      },
      {
        accessId: '5',
        accessLabel: 'DELETE',
        accessName: '删除权限',
        accessType: 'FUNC',
        accessRange: null,
      },
    ],
  },
} as any;

export const ProductVersionMockData = 'FASTMAIL';
