const testData = {
  name: '智能营销',
  path: 'intelliMarketing',
  children: [
    {
      name: '智能营销',
      path: 'intelliMarketing',
      label: '',
      children: [
        {
          name: '地址簿',
          path: 'addressBook',
          label: 'ADDRESS_BOOK',
          icon: {
            key: null,
            ref: null,
            props: {},
            _owner: null,
            _store: {},
          },
          children: [
            {
              name: '营销地址簿',
              path: 'addressBookIndex',
              label: 'ADDRESS_BOOK_LIST',
              topMenuIcon: {
                key: null,
                ref: null,
                props: {},
                _owner: null,
                _store: {},
              },
              parent: 'addressBook',
              children: [],
            },
            {
              name: '地址簿公海',
              path: 'addressBookOpenSea',
              label: 'ADDRESS_OPEN_SEA',
              topMenuIcon: {
                key: null,
                ref: null,
                props: {},
                _owner: null,
                _store: {},
              },
              parent: 'addressBook',
              children: [],
            },
            {
              name: '营销统计',
              path: 'addressBookDatastat',
              label: 'MARKET_DATA_STAT',
              topMenuIcon: {
                key: null,
                ref: null,
                props: {},
                _owner: null,
                _store: {},
              },
              parent: 'addressBook',
              children: [],
            },
          ],
        },
        {
          name: '邮件营销',
          path: 'edm',
          label: 'EDM',
          icon: {
            key: null,
            ref: null,
            props: {},
            _owner: null,
            _store: {},
          },
          children: [
            {
              name: '发件任务',
              path: 'index',
              label: 'EDM_SENDBOX',
              parent: 'edm',
              subset: ['write'],
              topMenuIcon: {
                key: null,
                ref: null,
                props: {},
                _owner: null,
                _store: {},
              },
              children: [],
            },
            {
              name: '草稿列表',
              path: 'drafts',
              label: 'EDM_DRAFT_LIST',
              parent: 'edm',
              topMenuIcon: {
                key: null,
                ref: null,
                props: {},
                _owner: null,
                _store: {},
              },
              children: [],
            },
            // {
            //   name: '自动化营销',
            //   path: 'autoMarketTask',
            //   label: 'EDM_SENDBOX',
            //   subset: ['autoMarketTaskEdit'],
            //   hiddenWithFree: true,
            //   show: true,
            //   parent: 'edm',
            //   topMenuIcon: {
            //     key: null,
            //     ref: null,
            //     props: {},
            //     _owner: null,
            //     _store: {},
            //   },
            //   children: [],
            // },
            {
              name: '邮件模板',
              path: 'mailTemplate',
              label: '',
              parent: 'edm',
              subset: ['templateAddModal'],
              topMenuIcon: {
                key: null,
                ref: null,
                props: {},
                _owner: null,
                _store: {},
              },
              children: [],
            },
            {
              name: '营销托管',
              path: 'aiHosting',
              label: 'EDM_SENDBOX',
              parent: 'edm',
              subset: ['aiHosting'],
              topMenuIcon: {
                key: null,
                ref: null,
                props: {},
                _owner: null,
                _store: {},
              },
              children: [],
              newBadge: true,
            },
          ],
        },
        {
          name: 'WhatsApp个人营销',
          path: 'personalWhatsapp',
          label: 'WHATSAPP',
          icon: {
            key: null,
            ref: null,
            props: {},
            _owner: null,
            _store: {},
          },
          children: [
            {
              name: '个人号消息',
              path: 'pernsonalWhatsapp',
              parent: 'personalWhatsapp',
              children: [],
              topMenuIcon: {
                key: null,
                ref: null,
                props: {},
                _owner: null,
                _store: {},
              },
              label: 'WHATSAPP_PERSONAL_MSG',
            },
            {
              name: '个人号群发任务',
              path: 'pernsonalJobWhatsApp',
              parent: 'personalWhatsapp',
              children: [],
              topMenuIcon: {
                key: null,
                ref: null,
                props: {},
                _owner: null,
                _store: {},
              },
              label: 'WHATSAPP_PERSONAL_SEND_TASK',
            },
          ],
        },
        {
          name: 'WhatsApp商业营销',
          path: 'whatsapp',
          label: 'WHATSAPP',
          icon: {
            key: null,
            ref: null,
            props: {},
            _owner: null,
            _store: {},
          },
          children: [
            {
              name: '商业号消息',
              path: 'whatsAppMessage',
              label: 'WHATSAPP_MSG',
              parent: 'whatsapp',
              topMenuIcon: {
                key: null,
                ref: null,
                props: {},
                _owner: null,
                _store: {},
              },
              children: [],
            },
            {
              name: '商业号群发任务',
              path: 'whatsAppJob',
              label: 'WHATSAPP_SEND_TASK',
              parent: 'whatsapp',
              subset: ['whatsAppJobEdit'],
              topMenuIcon: {
                key: null,
                ref: null,
                props: {},
                _owner: null,
                _store: {},
              },
              children: [],
            },
            {
              name: '数据统计',
              path: 'whatsAppStatistic',
              label: 'WHATSAPP_DATA_STAT',
              parent: 'whatsapp',
              show: false,
              topMenuIcon: {
                key: null,
                ref: null,
                props: {},
                _owner: null,
                _store: {},
              },
              children: [],
            },
            {
              name: '消息模板',
              path: 'whatsAppTemplate',
              label: 'WHATSAPP_MSG_TPL_SETTING',
              parent: 'whatsapp',
              show: false,
              topMenuIcon: {
                key: null,
                ref: null,
                props: {},
                _owner: null,
                _store: {},
              },
              children: [],
            },
          ],
        },
        {
          name: 'Facebook营销',
          path: 'facebook',
          label: 'FACEBOOK',
          icon: {
            key: null,
            ref: null,
            props: {},
            _owner: null,
            _store: {},
          },
          hiddenWithFree: true,
          children: [
            {
              name: '主页管理',
              path: 'facebookPages',
              parent: 'facebook',
              label: 'FACEBOOK_MY_MAIN_PAGE',
              children: [],
              topMenuIcon: {
                key: null,
                ref: null,
                props: {},
                _owner: null,
                _store: {},
              },
            },
            {
              name: '帖子评论',
              path: 'facebookPosts',
              parent: 'facebook',
              label: 'FACEBOOK_MY_POST',
              children: [],
              topMenuIcon: {
                key: null,
                ref: null,
                props: {},
                _owner: null,
                _store: {},
              },
            },
            {
              name: '消息',
              path: 'facebookMessage',
              parent: 'facebook',
              label: 'FACEBOOK_MSG',
              children: [],
              topMenuIcon: {
                key: null,
                ref: null,
                props: {},
                _owner: null,
                _store: {},
              },
            },
          ],
        },
      ],
    },
  ],
};
