const cmd = require('/Users/shishengb18701shishengcorp.netease.com/Documents/project/fr_for_work/sirius-desktop/node_modules/gatsby/dist/commands/develop-process.js');
const args = {
  _: ['develop'],
  p: '8000',
  port: 63530,
  H: '127.0.0.1',
  host: '127.0.0.1',
  verbose: true,
  'no-color': false,
  'no-colors': false,
  noColors: false,
  noColor: false,
  json: false,
  c: '',
  'cert-file': '',
  certFile: '',
  k: '',
  'key-file': '',
  keyFile: '',
  'ca-file': '',
  caFile: '',
  'graphql-tracing': false,
  graphqlTracing: false,
  $0: 'gatsby',
  directory: '/Users/shishengb18701shishengcorp.netease.com/Documents/project/fr_for_work/sirius-desktop/packages/web',
  browserslist: ['>0.25%', 'not dead'],
  sitePackageJson: {
    name: 'web',
    version: '1.0.0',
    private: true,
    description: 'My Gatsby Site',
    keywords: ['gatsby'],
    scripts: {
      develop: 'cross-env ACTIVE_ENV=develop gatsby develop --verbose',
      start: 'ACTIVE_ENV=develop gatsby develop -p 8000 -H 127.0.0.1 --verbose',
      'build:prod': 'cross-env ACTIVE_ENV=prod BUILD_FOR= gatsby build --verbose',
      'build:test': 'cross-env ACTIVE_ENV=test BUILD_FOR= gatsby build',
      'build:electron:test': 'cross-env ACTIVE_ENV=test BUILD_FOR=electron gatsby build',
      'build:electron:prod': 'cross-env ACTIVE_ENV=prod BUILD_FOR=electron gatsby build',
      serve: 'gatsby serve',
      clean: 'gatsby clean',
    },
    husky: { hooks: { 'pre-push': 'yarn build:test' } },
    dependencies: {
      '@ant-design/icons': '^4.4.0',
      '@loadable/component': '^5.14.1',
      '@svgr/webpack': '^5.5.0',
      '@types/loadable__component': '^5.13.1',
      '@types/mockjs': '^1.0.3',
      '@types/react-copy-to-clipboard': '^5.0.0',
      antd: '^4.10.3',
      classnames: '^2.2.6',
      'cross-env': '^7.0.3',
      gatsby: '^2.26.1',
      'gatsby-plugin-react-helmet': '^3.9.0',
      'gatsby-plugin-react-redux': '^1.1.0',
      'gatsby-plugin-sass': '^3.0.0',
      'gatsby-plugin-svgr': '^2.1.0',
      'gatsby-source-filesystem': '^2.11.0',
      'http-proxy': '^1.18.1',
      'http-proxy-middleware': '^1.0.6',
      husky: '^4.3.8',
      md5: '^2.3.0',
      mockjs: '^1.1.0',
      'node-sass': '^5.0.0',
      react: '^16.13.1',
      'react-copy-to-clipboard': '^5.0.3',
      'react-dom': '^16.13.1',
      'react-helmet': '^6.1.0',
      'react-hotkeys': '^2.0.0-pre9',
      'react-redux': '^7.2.2',
      'react-resizable': '^1.11.0',
      'react-sticky': '^6.0.3',
      'react-virtualized': '^9.22.3',
      redux: '^4.0.5',
      rsuite: '^4.8.8',
    },
    devDependencies: {
      '@types/classnames': '^2.2.11',
      '@types/md5': '^2.2.1',
      '@types/react-resizable': '^1.7.2',
      '@types/react-sticky': '^6.0.3',
      '@types/react-virtualized': '^9.21.11',
    },
  },
  report: { errorMap: {} },
  useYarn: true,
  proxyPort: 8000,
  ssl: null,
  debugInfo: null,
};
cmd(args);
