const compDes = [
  {
    tags: {},
    filePath: '/Users/lujiajianb27070/code/sirius-desktop/packages/web-common/src/components/UI/Button/index.tsx',
    description: '页面中最常用的的按钮元素，适合于完成特定的交互，支持 HTML button 和 a 链接 的所有属性',
    displayName: 'Button',
    methods: [],
    props: {
      className: {
        defaultValue: null,
        description: '用户自定义 css class',
        name: 'className',
        parent: { fileName: 'sirius-desktop/packages/web-common/src/components/UI/Button/button.tsx', name: 'BaseButtonProps' },
        declarations: [
          { fileName: 'sirius-desktop/packages/web-common/src/components/UI/Button/button.tsx', name: 'BaseButtonProps' },
          { fileName: 'sirius-desktop/node_modules/@types/react/index.d.ts', name: 'HTMLAttributes' },
        ],
        required: false,
        type: { name: 'string' },
      },
      disabled: {
        defaultValue: { value: false },
        description: '设置 Button 的禁用',
        name: 'disabled',
        parent: { fileName: 'sirius-desktop/packages/web-common/src/components/UI/Button/button.tsx', name: 'BaseButtonProps' },
        declarations: [
          { fileName: 'sirius-desktop/packages/web-common/src/components/UI/Button/button.tsx', name: 'BaseButtonProps' },
          { fileName: 'sirius-desktop/node_modules/@types/react/index.d.ts', name: 'ButtonHTMLAttributes' },
        ],
        required: false,
        type: { name: 'boolean' },
      },
      btnType: {
        defaultValue: { value: 'default' },
        description: '设置 Button 的类型',
        name: 'btnType',
        parent: { fileName: 'sirius-desktop/packages/web-common/src/components/UI/Button/button.tsx', name: 'BaseButtonProps' },
        declarations: [{ fileName: 'sirius-desktop/packages/web-common/src/components/UI/Button/button.tsx', name: 'BaseButtonProps' }],
        required: false,
        type: {
          name: 'enum',
          raw: 'ButtonType',
          value: [
            { value: '"link"' },
            { value: '"primary"' },
            { value: '"default"' },
            { value: '"minorWhite"' },
            { value: '"minorGray"' },
            { value: '"minorLine"' },
            { value: '"danger"' },
            { value: '"dashedLine"' },
          ],
        },
      },
      href: {
        defaultValue: null,
        description: 'link 类型按钮的跳转链接',
        name: 'href',
        parent: { fileName: 'sirius-desktop/packages/web-common/src/components/UI/Button/button.tsx', name: 'BaseButtonProps' },
        declarations: [
          { fileName: 'sirius-desktop/packages/web-common/src/components/UI/Button/button.tsx', name: 'BaseButtonProps' },
          { fileName: 'sirius-desktop/node_modules/@types/react/index.d.ts', name: 'AnchorHTMLAttributes' },
        ],
        required: false,
        type: { name: 'string' },
      },
      inline: {
        defaultValue: { value: false },
        description: '默认是false，button 的 display 为 flex，设置为 true 后，display 为 inline-flex',
        name: 'inline',
        parent: { fileName: 'sirius-desktop/packages/web-common/src/components/UI/Button/button.tsx', name: 'BaseButtonProps' },
        declarations: [{ fileName: 'sirius-desktop/packages/web-common/src/components/UI/Button/button.tsx', name: 'BaseButtonProps' }],
        required: false,
        type: { name: 'boolean' },
      },
      size: {
        defaultValue: { value: 'default' },
        description: '设置按钮大小',
        name: 'size',
        parent: { fileName: 'sirius-desktop/packages/web-common/src/components/UI/Button/button.tsx', name: 'BaseButtonProps' },
        declarations: [{ fileName: 'sirius-desktop/packages/web-common/src/components/UI/Button/button.tsx', name: 'BaseButtonProps' }],
        required: false,
        type: { name: 'enum', raw: 'Size', value: [{ value: '"default"' }, { value: '"mini"' }, { value: '"small"' }, { value: '"large"' }] },
      },
      loading: {
        defaultValue: { value: false },
        description: '设置按钮载入状态',
        name: 'loading',
        parent: { fileName: 'sirius-desktop/packages/web-common/src/components/UI/Button/button.tsx', name: 'BaseButtonProps' },
        declarations: [{ fileName: 'sirius-desktop/packages/web-common/src/components/UI/Button/button.tsx', name: 'BaseButtonProps' }],
        required: false,
        type: { name: 'boolean' },
      },
    },
  },
];
export default compDes;
