const compDes = [
  {
    tags: {},
    filePath: '/Users/lujiajianb27070/code/sirius-desktop/packages/web-common/src/components/UI/HollowOutGuideNew/index.tsx',
    description: '',
    displayName: 'HollowOutGuideNew',
    methods: [],
    props: {
      type: {
        defaultValue: null,
        description: '类型，1：蒙层引导，2：气泡图文，3：气泡单行引导。默认为蒙层引导',
        name: 'type',
        parent: {
          fileName: 'sirius-desktop/packages/web-common/src/components/UI/HollowOutGuideNew/hollowOutGuide.tsx',
          name: 'HollowOutGuideProps',
        },
        declarations: [{ fileName: 'sirius-desktop/packages/web-common/src/components/UI/HollowOutGuideNew/hollowOutGuide.tsx', name: 'HollowOutGuideProps' }],
        required: false,
        type: { name: 'string' },
      },
      enable: {
        defaultValue: null,
        description: '是否启用飘新引导，由业务控制',
        name: 'enable',
        parent: {
          fileName: 'sirius-desktop/packages/web-common/src/components/UI/HollowOutGuideNew/hollowOutGuide.tsx',
          name: 'HollowOutGuideProps',
        },
        declarations: [{ fileName: 'sirius-desktop/packages/web-common/src/components/UI/HollowOutGuideNew/hollowOutGuide.tsx', name: 'HollowOutGuideProps' }],
        required: false,
        type: { name: 'boolean' },
      },
      hash: {
        defaultValue: null,
        description:
          '引导生效的页面，设置后，会在路由到当前页面的时候，才会注册展示引导\n（发现使用引导的组件，存在误加载的问题，导致引导被注册，但是又无法展示，阻塞了其他引导的展示，这种场景，可以使用 hash 字段来约束）\n实例：#setting、#mailbox',
        name: 'hash',
        parent: {
          fileName: 'sirius-desktop/packages/web-common/src/components/UI/HollowOutGuideNew/hollowOutGuide.tsx',
          name: 'HollowOutGuideProps',
        },
        declarations: [{ fileName: 'sirius-desktop/packages/web-common/src/components/UI/HollowOutGuideNew/hollowOutGuide.tsx', name: 'HollowOutGuideProps' }],
        required: false,
        type: { name: 'string' },
      },
      guideId: {
        defaultValue: null,
        description: '唯一id，是存入 localstroage 的 key，不同的飘新引导必须保证 guideId 不同，同一个飘新引导的分步要保证 guideId 一致',
        name: 'guideId',
        parent: {
          fileName: 'sirius-desktop/packages/web-common/src/components/UI/HollowOutGuideNew/hollowOutGuide.tsx',
          name: 'HollowOutGuideProps',
        },
        declarations: [{ fileName: 'sirius-desktop/packages/web-common/src/components/UI/HollowOutGuideNew/hollowOutGuide.tsx', name: 'HollowOutGuideProps' }],
        required: true,
        type: { name: 'string' },
      },
      noneUserRelated: {
        defaultValue: null,
        description: '存入 localstroage 的 key 是否不关联 用户id，默认false，关联用户id',
        name: 'noneUserRelated',
        parent: {
          fileName: 'sirius-desktop/packages/web-common/src/components/UI/HollowOutGuideNew/hollowOutGuide.tsx',
          name: 'HollowOutGuideProps',
        },
        declarations: [{ fileName: 'sirius-desktop/packages/web-common/src/components/UI/HollowOutGuideNew/hollowOutGuide.tsx', name: 'HollowOutGuideProps' }],
        required: false,
        type: { name: 'boolean' },
      },
      step: {
        defaultValue: null,
        description: '分步，初始值为 1，注意 step 必须顺序不能间断',
        name: 'step',
        parent: {
          fileName: 'sirius-desktop/packages/web-common/src/components/UI/HollowOutGuideNew/hollowOutGuide.tsx',
          name: 'HollowOutGuideProps',
        },
        declarations: [{ fileName: 'sirius-desktop/packages/web-common/src/components/UI/HollowOutGuideNew/hollowOutGuide.tsx', name: 'HollowOutGuideProps' }],
        required: false,
        type: { name: 'number' },
      },
      title: {
        defaultValue: null,
        description: '引导弹窗标题',
        name: 'title',
        parent: {
          fileName: 'sirius-desktop/packages/web-common/src/components/UI/HollowOutGuideNew/hollowOutGuide.tsx',
          name: 'HollowOutGuideProps',
        },
        declarations: [{ fileName: 'sirius-desktop/packages/web-common/src/components/UI/HollowOutGuideNew/hollowOutGuide.tsx', name: 'HollowOutGuideProps' }],
        required: true,
        type: { name: 'ReactNode' },
      },
      intro: {
        defaultValue: null,
        description: '引导弹窗详情',
        name: 'intro',
        parent: {
          fileName: 'sirius-desktop/packages/web-common/src/components/UI/HollowOutGuideNew/hollowOutGuide.tsx',
          name: 'HollowOutGuideProps',
        },
        declarations: [{ fileName: 'sirius-desktop/packages/web-common/src/components/UI/HollowOutGuideNew/hollowOutGuide.tsx', name: 'HollowOutGuideProps' }],
        required: false,
        type: { name: 'string | Element' },
      },
      refresh: {
        defaultValue: null,
        description: 'refresh变更后，会重新刷新 引导弹窗的位置',
        name: 'refresh',
        parent: {
          fileName: 'sirius-desktop/packages/web-common/src/components/UI/HollowOutGuideNew/hollowOutGuide.tsx',
          name: 'HollowOutGuideProps',
        },
        declarations: [{ fileName: 'sirius-desktop/packages/web-common/src/components/UI/HollowOutGuideNew/hollowOutGuide.tsx', name: 'HollowOutGuideProps' }],
        required: false,
        type: { name: 'number' },
      },
      renderFooter: {
        defaultValue: null,
        description: '底部按钮',
        name: 'renderFooter',
        parent: {
          fileName: 'sirius-desktop/packages/web-common/src/components/UI/HollowOutGuideNew/hollowOutGuide.tsx',
          name: 'HollowOutGuideProps',
        },
        declarations: [{ fileName: 'sirius-desktop/packages/web-common/src/components/UI/HollowOutGuideNew/hollowOutGuide.tsx', name: 'HollowOutGuideProps' }],
        required: false,
        type: { name: 'Element' },
      },
      placement: {
        defaultValue: null,
        description: '引导弹窗位置',
        name: 'placement',
        parent: {
          fileName: 'sirius-desktop/packages/web-common/src/components/UI/HollowOutGuideNew/hollowOutGuide.tsx',
          name: 'HollowOutGuideProps',
        },
        declarations: [{ fileName: 'sirius-desktop/packages/web-common/src/components/UI/HollowOutGuideNew/hollowOutGuide.tsx', name: 'HollowOutGuideProps' }],
        required: false,
        type: {
          name: 'enum',
          raw: '"top" | "left" | "right" | "bottom" | "topLeft" | "topRight" | "bottomLeft" | "bottomRight" | "leftTop" | "leftBottom" | "rightTop" | "rightBottom"',
          value: [
            { value: '"top"' },
            { value: '"left"' },
            { value: '"right"' },
            { value: '"bottom"' },
            { value: '"topLeft"' },
            { value: '"topRight"' },
            { value: '"bottomLeft"' },
            { value: '"bottomRight"' },
            { value: '"leftTop"' },
            { value: '"leftBottom"' },
            { value: '"rightTop"' },
            { value: '"rightBottom"' },
          ],
        },
      },
      padding: {
        defaultValue: null,
        description: '目标元素的聚焦框 padding，通过修改 padding 可以优化聚焦框展示UI效果, [上,右,下,左]',
        name: 'padding',
        parent: {
          fileName: 'sirius-desktop/packages/web-common/src/components/UI/HollowOutGuideNew/hollowOutGuide.tsx',
          name: 'HollowOutGuideProps',
        },
        declarations: [{ fileName: 'sirius-desktop/packages/web-common/src/components/UI/HollowOutGuideNew/hollowOutGuide.tsx', name: 'HollowOutGuideProps' }],
        required: false,
        type: { name: 'number[]' },
      },
      borderRadius: {
        defaultValue: null,
        description: '目标元素的聚焦框的圆角，默认是6px',
        name: 'borderRadius',
        parent: {
          fileName: 'sirius-desktop/packages/web-common/src/components/UI/HollowOutGuideNew/hollowOutGuide.tsx',
          name: 'HollowOutGuideProps',
        },
        declarations: [{ fileName: 'sirius-desktop/packages/web-common/src/components/UI/HollowOutGuideNew/hollowOutGuide.tsx', name: 'HollowOutGuideProps' }],
        required: false,
        type: { name: 'number' },
      },
      targetWidth: {
        defaultValue: null,
        description: '目标元素宽度，可以自定义设置，不设置的话，会计算目标元素的宽度\ntargetWidth，targetHeight 是为了临时解决兼容性问题加的，后期会优化',
        name: 'targetWidth',
        parent: {
          fileName: 'sirius-desktop/packages/web-common/src/components/UI/HollowOutGuideNew/hollowOutGuide.tsx',
          name: 'HollowOutGuideProps',
        },
        declarations: [{ fileName: 'sirius-desktop/packages/web-common/src/components/UI/HollowOutGuideNew/hollowOutGuide.tsx', name: 'HollowOutGuideProps' }],
        required: false,
        type: { name: 'number' },
      },
      targetHeight: {
        defaultValue: null,
        description: '目标元素高度，可以自定义设置，不设置的话，会计算目标元素的高度',
        name: 'targetHeight',
        parent: {
          fileName: 'sirius-desktop/packages/web-common/src/components/UI/HollowOutGuideNew/hollowOutGuide.tsx',
          name: 'HollowOutGuideProps',
        },
        declarations: [{ fileName: 'sirius-desktop/packages/web-common/src/components/UI/HollowOutGuideNew/hollowOutGuide.tsx', name: 'HollowOutGuideProps' }],
        required: false,
        type: { name: 'number' },
      },
      arrowDistance: {
        defaultValue: null,
        description:
          // eslint-disable-next-line max-len
          "弹窗位置是'top' | 'bottom' | 'topLeft' | 'topRight' | 'bottomLeft' | 'bottomRight' 箭头距离左边框距离\n弹窗位置是'left' | 'right' | 'leftTop' | 'leftBottom' | 'rightTop' | 'rightBottom' 箭头距离上边框距离",
        name: 'arrowDistance',
        parent: {
          fileName: 'sirius-desktop/packages/web-common/src/components/UI/HollowOutGuideNew/hollowOutGuide.tsx',
          name: 'HollowOutGuideProps',
        },
        declarations: [{ fileName: 'sirius-desktop/packages/web-common/src/components/UI/HollowOutGuideNew/hollowOutGuide.tsx', name: 'HollowOutGuideProps' }],
        required: false,
        type: { name: 'number' },
      },
      okText: {
        defaultValue: null,
        description: '确认按钮文案，默认知道了',
        name: 'okText',
        parent: {
          fileName: 'sirius-desktop/packages/web-common/src/components/UI/HollowOutGuideNew/hollowOutGuide.tsx',
          name: 'HollowOutGuideProps',
        },
        declarations: [{ fileName: 'sirius-desktop/packages/web-common/src/components/UI/HollowOutGuideNew/hollowOutGuide.tsx', name: 'HollowOutGuideProps' }],
        required: false,
        type: { name: 'string' },
      },
      showSideBar: {
        defaultValue: null,
        description: '遮罩是否保留左边导航栏（暂时不可用，如要使用，请与我联系@lujiajian）',
        name: 'showSideBar',
        parent: {
          fileName: 'sirius-desktop/packages/web-common/src/components/UI/HollowOutGuideNew/hollowOutGuide.tsx',
          name: 'HollowOutGuideProps',
        },
        declarations: [{ fileName: 'sirius-desktop/packages/web-common/src/components/UI/HollowOutGuideNew/hollowOutGuide.tsx', name: 'HollowOutGuideProps' }],
        required: false,
        type: { name: 'boolean' },
      },
      showArrow: {
        defaultValue: null,
        description: '是否展示箭头',
        name: 'showArrow',
        parent: {
          fileName: 'sirius-desktop/packages/web-common/src/components/UI/HollowOutGuideNew/hollowOutGuide.tsx',
          name: 'HollowOutGuideProps',
        },
        declarations: [{ fileName: 'sirius-desktop/packages/web-common/src/components/UI/HollowOutGuideNew/hollowOutGuide.tsx', name: 'HollowOutGuideProps' }],
        required: false,
        type: { name: 'boolean' },
      },
      contentImg: {
        defaultValue: null,
        description: '气泡图文引导图片',
        name: 'contentImg',
        parent: {
          fileName: 'sirius-desktop/packages/web-common/src/components/UI/HollowOutGuideNew/hollowOutGuide.tsx',
          name: 'HollowOutGuideProps',
        },
        declarations: [{ fileName: 'sirius-desktop/packages/web-common/src/components/UI/HollowOutGuideNew/hollowOutGuide.tsx', name: 'HollowOutGuideProps' }],
        required: false,
        type: { name: 'string' },
      },
      onClose: {
        defaultValue: null,
        description: '关闭回调',
        name: 'onClose',
        parent: {
          fileName: 'sirius-desktop/packages/web-common/src/components/UI/HollowOutGuideNew/hollowOutGuide.tsx',
          name: 'HollowOutGuideProps',
        },
        declarations: [{ fileName: 'sirius-desktop/packages/web-common/src/components/UI/HollowOutGuideNew/hollowOutGuide.tsx', name: 'HollowOutGuideProps' }],
        required: false,
        type: { name: '() => void' },
      },
      children: {
        defaultValue: null,
        description: '目标元素, 只有文本节点会导致目标元素位置计算错误，所以目标元素文本最好被标签包裹',
        name: 'children',
        parent: {
          fileName: 'sirius-desktop/packages/web-common/src/components/UI/HollowOutGuideNew/hollowOutGuide.tsx',
          name: 'HollowOutGuideProps',
        },
        declarations: [
          { fileName: 'sirius-desktop/packages/web-common/src/components/UI/HollowOutGuideNew/hollowOutGuide.tsx', name: 'HollowOutGuideProps' },
          { fileName: 'sirius-desktop/node_modules/@types/react/index.d.ts', name: 'TypeLiteral' },
        ],
        required: false,
        type: { name: 'ReactNode' },
      },
      childrenRef: {
        defaultValue: null,
        description: '目标元素ref，通过目标元素Ref判断children dom 是否已经在视窗内，在视窗内则注册引导，解决引导被错误的提前注册的问题',
        name: 'childrenRef',
        parent: {
          fileName: 'sirius-desktop/packages/web-common/src/components/UI/HollowOutGuideNew/hollowOutGuide.tsx',
          name: 'HollowOutGuideProps',
        },
        declarations: [{ fileName: 'sirius-desktop/packages/web-common/src/components/UI/HollowOutGuideNew/hollowOutGuide.tsx', name: 'HollowOutGuideProps' }],
        required: false,
        type: { name: 'MutableRefObject<any>' },
      },
    },
  },
];
export default compDes;
