import React from 'react';
import USSrc from '@/images/flag/US.png';
import MXSrc from '@/images/flag/MX.png';
import GTSrc from '@/images/flag/GT.png';
import CRSrc from '@/images/flag/CR.png';
import PASrc from '@/images/flag/PA.png';
import BOSrc from '@/images/flag/BO.png';
import BRSrc from '@/images/flag/BR.png';
import CLSrc from '@/images/flag/CL.png';
import COSrc from '@/images/flag/CO.png';
import ECSrc from '@/images/flag/EC.png';
import PYSrc from '@/images/flag/PY.png';
import PESrc from '@/images/flag/PE.png';
import UYSrc from '@/images/flag/UY.png';
import VESrc from '@/images/flag/VE.png';
import ARSrc from '@/images/flag/AR.png';
import JPSrc from '@/images/flag/JP.png';
import SGSrc from '@/images/flag/SG.png';
import MYSrc from '@/images/flag/MY.png';
import INSrc from '@/images/flag/IN.png';
import PKSrc from '@/images/flag/PK.png';
import LKSrc from '@/images/flag/LK.png';
import IDSrc from '@/images/flag/ID.png';
import VNSrc from '@/images/flag/VN.png';
import PHSrc from '@/images/flag/PH.png';
import KZSrc from '@/images/flag/KZ.png';
import UZSrc from '@/images/flag/UZ.png';
import GBSrc from '@/images/flag/GB.png';
import RUSrc from '@/images/flag/RU.png';
import DESrc from '@/images/flag/DE.png';
import FRSrc from '@/images/flag/FR.png';
import ESSrc from '@/images/flag/ES.png';
import ITSrc from '@/images/flag/IT.png';
import CHSrc from '@/images/flag/CH.png';
import UASrc from '@/images/flag/UA.png';
import ETSrc from '@/images/flag/ET.png';
import UGSrc from '@/images/flag/UG.png';
import KESrc from '@/images/flag/KE.png';

const MapImage = (props: any) => {
  return <img src={props.src} width={18} height={12} style={{ paddingRight: 4, objectFit: 'contain' }} alt="map-image" />;
};
const US = () => <MapImage src={USSrc} />;
const MX = () => <MapImage src={MXSrc} />;
const GT = () => <MapImage src={GTSrc} />;
const CR = () => <MapImage src={CRSrc} />;
const PA = () => <MapImage src={PASrc} />;
const BO = () => <MapImage src={BOSrc} />;
const BR = () => <MapImage src={BRSrc} />;
const CL = () => <MapImage src={CLSrc} />;
const CO = () => <MapImage src={COSrc} />;
const EC = () => <MapImage src={ECSrc} />;
const PY = () => <MapImage src={PYSrc} />;
const PE = () => <MapImage src={PESrc} />;
const UY = () => <MapImage src={UYSrc} />;
const VE = () => <MapImage src={VESrc} />;
const AR = () => <MapImage src={ARSrc} />;
const JP = () => <MapImage src={JPSrc} />;
const SG = () => <MapImage src={SGSrc} />;
const MY = () => <MapImage src={MYSrc} />;
const IN = () => <MapImage src={INSrc} />;
const PK = () => <MapImage src={PKSrc} />;
const LK = () => <MapImage src={LKSrc} />;
const ID = () => <MapImage src={IDSrc} />;
const VN = () => <MapImage src={VNSrc} />;
const PH = () => <MapImage src={PHSrc} />;
const KZ = () => <MapImage src={KZSrc} />;
const UZ = () => <MapImage src={UZSrc} />;
const GB = () => <MapImage src={GBSrc} />;
const RU = () => <MapImage src={RUSrc} />;
const DE = () => <MapImage src={DESrc} />;
const FR = () => <MapImage src={FRSrc} />;
const ES = () => <MapImage src={ESSrc} />;
const IT = () => <MapImage src={ITSrc} />;
const CH = () => <MapImage src={CHSrc} />;
const UA = () => <MapImage src={UASrc} />;
const ET = () => <MapImage src={ETSrc} />;
const UG = () => <MapImage src={UGSrc} />;
const KE = () => <MapImage src={KESrc} />;
export { US, MX, GT, CR, PA, BO, BR, CL, CO, EC, PY, PE, UY, VE, AR, JP, SG, MY, IN, PK, LK, ID, VN, PH, KZ, UZ, GB, RU, DE, FR, ES, IT, CH, UA, ET, UG, KE };
