const compDes = [
  {
    tags: {},
    filePath: '/Users/lujiajianb27070/code/sirius-desktop/packages/web-common/src/components/UI/Tag/index.tsx',
    description: '',
    displayName: 'Tag',
    methods: [],
    props: {
      type: {
        defaultValue: null,
        description:
          // eslint-disable-next-line max-len
          'UI提供的固定六个颜色\nlabel-1-1: 背景颜色为label-1-1，文字颜色为label-1-3，描边颜色为label-1-2\nlabel-2-1: 背景颜色为label-2-1，文字颜色为label-2-3，描边颜色为label-2-2\nlabel-3-1: 背景颜色为label-3-1，文字颜色为label-3-3，描边颜色为label-3-2\nlabel-4-1: 背景颜色为label-4-1，文字颜色为label-4-3，描边颜色为label-4-2\nlabel-5-1: 背景颜色为label-5-1，文字颜色为label-5-3，描边颜色为label-5-2\nlabel-1-1: 背景颜色为label-6-1，文字颜色为label-6-3，描边颜色为label-6-2',
        name: 'type',
        parent: { fileName: 'sirius-desktop/packages/web-common/src/components/UI/Tag/tag.tsx', name: 'TagProps' },
        declarations: [{ fileName: 'sirius-desktop/packages/web-common/src/components/UI/Tag/tag.tsx', name: 'TagProps' }],
        required: false,
        type: {
          name: 'enum',
          raw: '"label-1-1" | "label-2-1" | "label-3-1" | "label-4-1" | "label-5-1" | "label-6-1"',
          value: [
            { value: '"label-1-1"' },
            { value: '"label-2-1"' },
            { value: '"label-3-1"' },
            { value: '"label-4-1"' },
            { value: '"label-5-1"' },
            { value: '"label-6-1"' },
          ],
        },
      },
      bgColor: {
        defaultValue: null,
        description: '背景颜色',
        name: 'bgColor',
        parent: { fileName: 'sirius-desktop/packages/web-common/src/components/UI/Tag/tag.tsx', name: 'TagProps' },
        declarations: [{ fileName: 'sirius-desktop/packages/web-common/src/components/UI/Tag/tag.tsx', name: 'TagProps' }],
        required: false,
        type: { name: 'string' },
      },
      fontColor: {
        defaultValue: null,
        description: '文字颜色',
        name: 'fontColor',
        parent: { fileName: 'sirius-desktop/packages/web-common/src/components/UI/Tag/tag.tsx', name: 'TagProps' },
        declarations: [{ fileName: 'sirius-desktop/packages/web-common/src/components/UI/Tag/tag.tsx', name: 'TagProps' }],
        required: false,
        type: { name: 'string' },
      },
      borderColor: {
        defaultValue: null,
        description: '描边颜色',
        name: 'borderColor',
        parent: { fileName: 'sirius-desktop/packages/web-common/src/components/UI/Tag/tag.tsx', name: 'TagProps' },
        declarations: [{ fileName: 'sirius-desktop/packages/web-common/src/components/UI/Tag/tag.tsx', name: 'TagProps' }],
        required: false,
        type: { name: 'string' },
      },
      height: {
        defaultValue: null,
        description: '标签高度，默认是20',
        name: 'height',
        parent: { fileName: 'sirius-desktop/packages/web-common/src/components/UI/Tag/tag.tsx', name: 'TagProps' },
        declarations: [{ fileName: 'sirius-desktop/packages/web-common/src/components/UI/Tag/tag.tsx', name: 'TagProps' }],
        required: false,
        type: { name: 'number' },
      },
      width: {
        defaultValue: null,
        description: '宽度，默认是根据内容的长度 + 左右 padding 6px',
        name: 'width',
        parent: { fileName: 'sirius-desktop/packages/web-common/src/components/UI/Tag/tag.tsx', name: 'TagProps' },
        declarations: [{ fileName: 'sirius-desktop/packages/web-common/src/components/UI/Tag/tag.tsx', name: 'TagProps' }],
        required: false,
        type: { name: 'number' },
      },
      borderRadius: {
        defaultValue: null,
        description: '圆角， 默认是2',
        name: 'borderRadius',
        parent: { fileName: 'sirius-desktop/packages/web-common/src/components/UI/Tag/tag.tsx', name: 'TagProps' },
        declarations: [{ fileName: 'sirius-desktop/packages/web-common/src/components/UI/Tag/tag.tsx', name: 'TagProps' }],
        required: false,
        type: { name: 'number' },
      },
      hideBorder: {
        defaultValue: null,
        description: '隐藏描边',
        name: 'hideBorder',
        parent: { fileName: 'sirius-desktop/packages/web-common/src/components/UI/Tag/tag.tsx', name: 'TagProps' },
        declarations: [{ fileName: 'sirius-desktop/packages/web-common/src/components/UI/Tag/tag.tsx', name: 'TagProps' }],
        required: false,
        type: { name: 'boolean' },
      },
      closable: {
        defaultValue: null,
        description: '标签是否可以关闭',
        name: 'closable',
        parent: { fileName: 'sirius-desktop/packages/web-common/src/components/UI/Tag/tag.tsx', name: 'TagProps' },
        declarations: [{ fileName: 'sirius-desktop/packages/web-common/src/components/UI/Tag/tag.tsx', name: 'TagProps' }],
        required: false,
        type: { name: 'boolean' },
      },
      onClose: {
        defaultValue: null,
        description: '关闭回调',
        name: 'onClose',
        parent: { fileName: 'sirius-desktop/packages/web-common/src/components/UI/Tag/tag.tsx', name: 'TagProps' },
        declarations: [{ fileName: 'sirius-desktop/packages/web-common/src/components/UI/Tag/tag.tsx', name: 'TagProps' }],
        required: false,
        type: { name: '() => void' },
      },
      children: {
        defaultValue: null,
        description: '目标元素',
        name: 'children',
        parent: { fileName: 'sirius-desktop/packages/web-common/src/components/UI/Tag/tag.tsx', name: 'TagProps' },
        declarations: [
          { fileName: 'sirius-desktop/packages/web-common/src/components/UI/Tag/tag.tsx', name: 'TagProps' },
          { fileName: 'sirius-desktop/node_modules/@types/react/index.d.ts', name: 'TypeLiteral' },
        ],
        required: false,
        type: { name: 'ReactNode' },
      },
    },
  },
];
export default compDes;
