import React from 'react';
import { Tooltip } from 'antd';
import IconCard, { iconMap } from '@web-common/components/UI/IconCard/index';
import styles from './icon.module.scss';

const iconList: { type: keyof typeof iconMap; props?: any }[] = [
  { type: 'jiantouyidong' },
  { type: 'tongyong_cuowutishi_xian' },
  { type: 'tongyong_qingchu' },
  { type: 'tongyong_youxiang2' },
  { type: 'tongyong_jiantou_shang' },
  { type: 'tongyong_zuixiaohua2' },
  { type: 'tongyong_caogao' },
  { type: 'tongyong_shezhi' },
  { type: 'tongyong_dizhibu' },
  { type: 'tongyong_xiansuo' },
  { type: 'tongyong_xiaoxi' },
  { type: 'tongyong_baocun' },
  { type: 'tongyong_fangda' },
  { type: 'tongyong_fanyi' },
  { type: 'tongyong_shuoming_mian' },
  { type: 'tongyong_dingyuechenggong' },
  { type: 'tongyong_rili3' },
  { type: 'tongyong_tianjia' },
  { type: 'tongyong_biaoqian_mian' },
  { type: 'tongyong_shift' },
  { type: 'tongyong_kuaijie' },
  { type: 'tongyong_dianzan_mianxing' },
  { type: 'bianji_juhe' },
  { type: 'tongyong_jiantou_you1' },
  { type: 'tongyong_rili2' },
  { type: 'tongyong_daochu' },
  { type: 'tongyong_dingyuerili' },
  { type: 'tongyong_fuzhi' },
  { type: 'tongyong_biaoqing' },
  { type: 'tongyong_jiantou_zuo1' },
  { type: 'tongyong_dizhi' },
  { type: 'tongyong_xuanzhuan' },
  { type: 'jichu_jiagou' },
  { type: 'schedule' },
  { type: 'tongyong_youxiang4' },
  { type: 'tongyong_shanchu_mian1' },
  { type: 'tongyong_chanpinguanli' },
  { type: 'tongyong_jiantou_shang1' },
  { type: 'tongyong_xiaoxi3_xian1' },
  { type: 'tongyong_xingxing_mian' },
  { type: 'tongyong_shouji' },
  { type: 'tongyong_lianjie' },
  { type: 'tongyong_renwu1' },
  { type: 'tongyong_bianji_mian' },
  { type: 'tongyong_youxiang5_xian' },
  { type: 'tongyong_qiye' },
  { type: 'tongyong_youxiang6' },
  { type: 'tongyong_dulichuangkou' },
  { type: 'tongyong_shezhi2_mian' },
  { type: 'bianji_huifu' },
  { type: 'tongyong_shaixuan' },
  { type: 'tongyong_yuyin' },
  { type: 'tongyong_shuangjiantou_shang' },
  { type: 'tongyong_renyuan10' },
  { type: 'tongyong_paizhao' },
  { type: 'tongyong_biaoqian2_xian' },
  { type: 'tongyong_yiwen_mian' },
  { type: 'tongyong_youxian' },
  { type: 'tongyong_diqiu' },
  { type: 'tongyong_houtai' },
  { type: 'tongyong_gongju' },
  { type: 'bianji_hongqi_xian' },
  { type: 'tongyong_renyuan11' },
  { type: 'tongyong_fasong' },
  { type: 'tongyong_zuixiaohua' },
  { type: 'tongyong_renwu' },
  { type: 'tongyong_shijian_xian' },
  { type: 'tongyong_ocr' },
  { type: 'tongyong_shuru' },
  { type: 'tongyong_xiaoxi3_xian' },
  { type: 'tongyong_shoujianxiang' },
  { type: 'tongyong_zhankai_xian' },
  { type: 'tongyong_shangchuan' },
  { type: 'tongyong_wenjianjia' },
  { type: 'tongyong_zuidahua' },
  { type: 'tongyong_kuaijiejian' },
  { type: 'tongyong_zuidahua2' },
  { type: 'tongyong_queren' },
  { type: 'tongyong_suo_guan' },
  { type: 'tongyong_shangchuan2_xian' },
  { type: 'tongyong_faqizhe' },
  { type: 'tongyong_quxiaozhiding' },
  { type: 'tongyong_tianjia_xian' },
  { type: 'tongyong_rili' },
  { type: 'tongyong_command' },
  { type: 'tongyong_chenggong_xian' },
  { type: 'tongyong_gengduo2' },
  { type: 'tongyong_guanbi_xian' },
  { type: 'tongyong_wangluoyichang_xian' },
  { type: 'tongyong_renyuan9' },
  { type: 'tongyong_shanchu_xian' },
  { type: 'tongyong_gaojisousuo' },
  { type: 'tongyong_bofang' },
  { type: 'tongyong_shuju' },
  { type: 'tongyong_renyuan8' },
  { type: 'tongyong_jianshao' },
  { type: 'tongyong_chanpin2' },
  { type: 'tongyong_xunhuan' },
  { type: 'tongyong_jingshi' },
  { type: 'tongyong_zhankai_shang' },
  { type: 'tongyong_tupian' },
  { type: 'tongyong_zhankai_you' },
  { type: 'tongyong_renyuan5' },
  { type: 'tongyong_biaoqian_xian' },
  { type: 'tongyong_lishijilu' },
  { type: 'tongyong_wendang' },
  { type: 'jiantoujinyong' },
  { type: 'tongyong_renyuan4' },
  { type: 'tongyong_shijian_mianxing' },
  { type: 'tongyong_fenxiang' },
  { type: 'tongyong_xunzhang' },
  { type: 'tongyong_shuangjiantou_zuo' },
  { type: 'tongyong_shouqi_xian' },
  { type: 'tongyong_yuedu' },
  { type: 'tongyong_fasong_mianxing' },
  { type: 'tongyong_cuowutishi_mian' },
  { type: 'tongyong_renyuan6' },
  { type: 'tongyong_shuaxin' },
  { type: 'tongyong_zhankai_xia' },
  { type: 'bianji_zhuanfa' },
  { type: 'tongyong_mokuai' },
  { type: 'tongyong_yingwen' },
  { type: 'tongyong_renyuan7' },
  { type: 'tongyong_lianglan' },
  { type: 'tongyong_daoru' },
  { type: 'tongyong_shuju2' },
  { type: 'shuruguangbiao' },
  { type: 'tongyong_shuoming_xian' },
  { type: 'tongyong_bangzhufankui' },
  { type: 'tongyong_xiaoxi2_mian1' },
  { type: 'tongyong_xinjianwenjianjia' },
  { type: 'tongyong_diannao' },
  { type: 'tongyong_renyuan3' },
  { type: 'tongyong_shujutongji' },
  { type: 'tongyong_youxiang5_mian' },
  { type: 'tongyong_shezhi2_xian' },
  { type: 'tongyong_renyuan2' },
  { type: 'tongyong_zhaiyao' },
  { type: 'tongyong_whatsapp' },
  { type: 'tongyong_yiwen' },
  { type: 'tongyong_xianshi' },
  { type: 'tongyong_zhongwen' },
  { type: 'tongyong_jiantou_zuo' },
  { type: 'tongyong_youxiang' },
  { type: 'tongyong_jilu' },
  { type: 'tongyong_zhiding' },
  { type: 'tongyong_gengduo' },
  { type: 'tongyong_kongxian' },
  { type: 'tongyong_renyuan1' },
  { type: 'tongyong_xingxing_xian' },
  { type: 'tongyong_wendang3' },
  { type: 'tongyong_moban' },
  { type: 'tongyong_jiazai' },
  { type: 'tongyong_jiantou_xia1' },
  { type: 'tongyong_yidong1' },
  { type: 'tongyong_sousuo' },
  { type: 'tongyong_shanchu' },
  { type: 'tongyong_dizhibu2' },
  { type: 'tongyong_shuangjiantou_you' },
  { type: 'tongyong_xiaoxi2_mian' },
  { type: 'tongyong_zijin' },
  { type: 'tongyong_paixu' },
  { type: 'tongyong_delete' },
  { type: 'tongyong_youxiang_mian' },
  { type: 'tongyong_zhongmingming' },
  { type: 'tongyong_gonggao' },
  { type: 'tongyong_zhankai_zuo' },
  { type: 'tongyong_dianzan_xianxing' },
  { type: 'tongyong_tixing' },
  { type: 'tongyong_quxiaotixing' },
  { type: 'tongyong_shuangjiantou_xia' },
  { type: 'bianji_hongqi_mian' },
  { type: 'tongyong_yun' },
  { type: 'tongyong_xiazai2_mian' },
  { type: 'tongyong_quanbu' },
  { type: 'tongyong_wangluoyichang_mian' },
  { type: 'tongyong_yincang' },
  { type: 'tongyong_jiantou_xia' },
  { type: 'tongyong_daoru1' },
  { type: 'tongyong_fuxuankuang' },
  { type: 'tongyong_daochu1' },
  { type: 'tongyong_shangchuan2_xian1' },
  { type: 'tongyong_shanchu_mian' },
  { type: 'tongyong_chehui' },
  { type: 'tongyong_jianshao_xian' },
  { type: 'tongyong_yidong' },
  { type: 'tongyong_liebiao' },
  { type: 'tongyong_zanting' },
  { type: 'tongyong_enter' },
  { type: 'tongyong_suo_kai' },
  { type: 'bianji_hongqi2_xian' },
  { type: 'tongyong_xiazai_mian' },
  { type: 'tongyong_sanlan' },
  { type: 'tongyong_yidu' },
  { type: 'tongyong_fanhuichuangkou' },
  { type: 'tongyong_shangchuan2_mian' },
  { type: 'tongyong_xiazai' },
  { type: 'tongyong_huiyuan' },
  { type: 'tongyong_jiantou_you' },
  { type: 'tongyong_fujian' },
  { type: 'tongyong_chenggong_mian' },
  { type: 'tongyong_wenjianjia2' },
  { type: 'tongyong_shouqi' },
  { type: 'tongyong_huifuquanbu' },
];
const NewIcons: React.FC = () => {
  return (
    <div className={styles.iconBox}>
      {iconList.map(icon => {
        return (
          <div className={styles.iconItem}>
            <p className={styles.iconSvg}>
              <IconCard type={icon.type} {...icon.props} />
            </p>
            <Tooltip title={icon.type}>
              <p className={styles.iconTxt}>{icon.type}</p>
            </Tooltip>
          </div>
        );
      })}
    </div>
  );
};

export default NewIcons;
