const compDes = [
  {
    tags: {},
    filePath: '/Users/lujiajianb27070/code/sirius-desktop/packages/web-common/src/components/UI/SiriusBadge/index.tsx',
    description: '',
    displayName: 'SiriusBadge',
    methods: [],
    props: {
      color: {
        defaultValue: null,
        description: '自定义小圆点的颜色',
        name: 'color',
        parent: { fileName: 'sirius-desktop/packages/web-common/src/components/UI/SiriusBadge/badge.tsx', name: 'IBadgeProps' },
        declarations: [{ fileName: 'sirius-desktop/packages/web-common/src/components/UI/SiriusBadge/badge.tsx', name: 'IBadgeProps' }],
        required: false,
        type: { name: 'string' },
      },
      count: {
        defaultValue: null,
        // eslint-disable-next-line no-template-curly-in-string
        description: '展示的数字，大于 overflowCount 时显示为 ${overflowCount}+，为 0 时隐藏',
        name: 'count',
        parent: { fileName: 'sirius-desktop/packages/web-common/src/components/UI/SiriusBadge/badge.tsx', name: 'IBadgeProps' },
        declarations: [{ fileName: 'sirius-desktop/packages/web-common/src/components/UI/SiriusBadge/badge.tsx', name: 'IBadgeProps' }],
        required: false,
        type: { name: 'ReactNode' },
      },
      dot: {
        defaultValue: { value: false },
        description: '不展示数字，只有一个小红点',
        name: 'dot',
        parent: { fileName: 'sirius-desktop/packages/web-common/src/components/UI/SiriusBadge/badge.tsx', name: 'IBadgeProps' },
        declarations: [{ fileName: 'sirius-desktop/packages/web-common/src/components/UI/SiriusBadge/badge.tsx', name: 'IBadgeProps' }],
        required: false,
        type: { name: 'boolean' },
      },
      offset: {
        defaultValue: null,
        description: '设置状态点的位置偏移',
        name: 'offset',
        parent: { fileName: 'sirius-desktop/packages/web-common/src/components/UI/SiriusBadge/badge.tsx', name: 'IBadgeProps' },
        declarations: [{ fileName: 'sirius-desktop/packages/web-common/src/components/UI/SiriusBadge/badge.tsx', name: 'IBadgeProps' }],
        required: false,
        type: { name: '[number, number]' },
      },
      overflowCount: {
        defaultValue: { value: 99 },
        description: '展示封顶的数字值',
        name: 'overflowCount',
        parent: { fileName: 'sirius-desktop/packages/web-common/src/components/UI/SiriusBadge/badge.tsx', name: 'IBadgeProps' },
        declarations: [{ fileName: 'sirius-desktop/packages/web-common/src/components/UI/SiriusBadge/badge.tsx', name: 'IBadgeProps' }],
        required: false,
        type: { name: 'number' },
      },
      showZero: {
        defaultValue: { value: false },
        description: '当数值为 0 时，是否展示 Badge',
        name: 'showZero',
        parent: { fileName: 'sirius-desktop/packages/web-common/src/components/UI/SiriusBadge/badge.tsx', name: 'IBadgeProps' },
        declarations: [{ fileName: 'sirius-desktop/packages/web-common/src/components/UI/SiriusBadge/badge.tsx', name: 'IBadgeProps' }],
        required: false,
        type: { name: 'boolean' },
      },
      dotSize: {
        defaultValue: { value: 'default' },
        description: '设置状态点的大小 default 宽高8px small 宽高6px',
        name: 'dotSize',
        parent: { fileName: 'sirius-desktop/packages/web-common/src/components/UI/SiriusBadge/badge.tsx', name: 'IBadgeProps' },
        declarations: [{ fileName: 'sirius-desktop/packages/web-common/src/components/UI/SiriusBadge/badge.tsx', name: 'IBadgeProps' }],
        required: false,
        type: { name: 'enum', raw: '"default" | "small"', value: [{ value: '"default"' }, { value: '"small"' }] },
      },
      intro: {
        defaultValue: { value: '' },
        description: '设置文本徽标',
        name: 'intro',
        parent: { fileName: 'sirius-desktop/packages/web-common/src/components/UI/SiriusBadge/badge.tsx', name: 'IBadgeProps' },
        declarations: [{ fileName: 'sirius-desktop/packages/web-common/src/components/UI/SiriusBadge/badge.tsx', name: 'IBadgeProps' }],
        required: false,
        type: { name: 'string' },
      },
      className: {
        defaultValue: null,
        description: '用户自定义 css class',
        name: 'className',
        parent: { fileName: 'sirius-desktop/packages/web-common/src/components/UI/SiriusBadge/badge.tsx', name: 'IBadgeProps' },
        declarations: [{ fileName: 'sirius-desktop/packages/web-common/src/components/UI/SiriusBadge/badge.tsx', name: 'IBadgeProps' }],
        required: false,
        type: { name: 'string' },
      },
    },
  },
];
export default compDes;
