export default {
  dataHttpApi: 'dataHttpApi',
  defaultDataStoreApiImpl: 'dataStoreApi',
  defaultSystemApiImpl: 'systemApi',
  defaultEventApi: 'eventApi',
  defaultFileApi: 'defaultFileApi',
  loginApiImpl: 'loginApi',
  contactApiImpl: 'contactApi',
  contactRealApiImpl: 'contactRealApiImpl',
  contactApiEventImpl: 'contactEventApi',
  contactApiWorkerImpl: 'contactWorkerApi',
  contactDbImpl: 'contact_db_impl',
  mailApiImpl: 'mailApiImpl',
  imTeamApiImpl: 'imTeamApiImpl',
  imDiscussApiImpl: 'imDiscussApiImpl',
  newDbApiImpl: 'newDbApi',
  catalogApiImpl: 'catalogApi',
  icsApiImpl: 'icsApiImpl',
  pushApiImpl: 'pushApiImpl',
  imApiImpl: 'NIM',
  upgradeAppApiImpl: 'upgradeAppApiImpl',
  mailConfApiImpl: 'mailConfApiImpl',
  mailSignatureImplApi: 'mailSignatureImplApi',
  mailTemplateImplApi: 'mailTemplateImplApi',
  mailProductImplApi: 'mailProductImplApi',
  netStorageImpl: 'netStorageImpl',
  netStorageShareImpl: 'netStorageShareImpl',
  errorReportImpl: 'errorReportImpl',
  dataTrackerApiImp: 'dataTrackerApiImp',
  dexieDbApi: 'dexieDbApi',
  dbCacheApiImpl: 'dbCacheApiImpl',
  dbInterfaceApiImpl: 'dbInterfaceApiImpl',
  dbMemoryApiImpl: 'dbMemoryApiImpl',
  configSettingApiImpl: 'configSettingApiImpl',
  htmlApi: 'htmlApiImpl',
  loggerApiImpl: 'loggerApiImpl',
  taskApiImpl: 'taskApiImpl',
  keyboardApiImpl: 'keyboardApiImpl',
  kfApiImpl: 'kfApiImpl',
  convertApiImpl: 'convertApiImpl',
  registerApiImpl: 'registerApiImpl',
  accountApiImpl: 'accountApiImpl',
  productAuthApiImpl: 'productAuthApiImpl',
  performanceImpl: 'performanceImpl',
  mailPraiseApiImpl: 'mailPraiseApiImpl',
  mailDraftApiImpl: 'mailDraftApiImpl',
  mailStrangerApiImpl: 'mailStrangerApiImpl',
  autoReplyApiImpl: 'autoReplyApiImpl', // 自动回复
  feedbackApiImpl: 'feedbackApiImpl',

  edmSendBoxApiImpl: 'edmSendboxApiImp',
  customerApiImpl: 'customerApiImpl',
  edmRoleApiImpl: 'edmRoleApiImpl',
  worktableApiImpl: 'worktableApiImpl',
  taskCenterApiImpl: 'taskCenterApiImpl',
  edmCustomsApiImpl: 'edmCustomsApiImpl',
  fieldSettingApiImpl: 'fieldSettingApiImpl',
  saleStageApiImpl: 'saleStageApiImpl',
  whatsAppApiImpl: 'whatsAppApiImpl',
  insertWhatsAppApiImpl: 'insertWhatsAppApiImpl',
  facebookApiImpl: 'facebookApiImpl',
  snsMarketingApiImpl: 'snsMarketingApiImpl',
  materielApiImpl: 'materielApiImpl',

  globalSearchApiImpl: 'globalSearchApiImpl',
  customerDiscoveryApi: 'customerDiscoveryApi',
  edmNotifyApiImpl: 'edmNotifyApiImpl',
  salesPitchApiImpl: 'salesPitchApiImpl',
  mailPlusCustomerApiImpl: 'mailPlusCustomerApiImpl',

  mailBlacklistApiImpl: 'mailBlacklistApiImpl',
  taskMailImplApi: 'taskMailImplApi',
  webmailApiImpl: 'webmailApiImpl',
  autoMarketApiImpl: 'autoMarketApiImpl',
  addressBookApiImpl: 'addressBookApiImpl',
  addressBookNewApiImpl: 'addressBookNewApiImpl',
  edmProductDataImpl: 'edmProductDataImpl',
  advertApiImpl: 'advertApiImpl',
  siteApiImpl: 'siteApiImpl',
  aiHostingApiImpl: 'aiHostingApiImpl',
  ffmsApi: 'ffmsApi',
  edmMenusApiImpl: 'edmMenusApiImpl',

  autoTestApi: 'autoTestApi',

  globalGuideApiImpl: 'globalGuideApiImpl',
  remindersImpl: 'remindersImpl',
};
