const CORP_MAIL_MAILAPI_PREFIX = '/corp-mail/mail/api/mail';
export default {
  corpMailGetAllFolders: `${CORP_MAIL_MAILAPI_PREFIX}/folders`, // 邮箱文件夹
  corpMailListMessages: `${CORP_MAIL_MAILAPI_PREFIX}/messages`, // 邮件列表
  corpMailReadMessage: `${CORP_MAIL_MAILAPI_PREFIX}/message`, // 邮件详情
  corpMailComponse: `${CORP_MAIL_MAILAPI_PREFIX}/compose`, // 写信
  corpMailCancel: `${CORP_MAIL_MAILAPI_PREFIX}/cancelDeliver`, // 取消写信
  corpMailImmediateDeliver: `${CORP_MAIL_MAILAPI_PREFIX}/immediateDeliver`, // 立即发信
  corpMailDeleteMail: `${CORP_MAIL_MAILAPI_PREFIX}/messages/delete`, // 删除邮件
  corpMailReplyMail: `${CORP_MAIL_MAILAPI_PREFIX}/message/reply`, // 回复邮件
  corpMailForwardMessages: `${CORP_MAIL_MAILAPI_PREFIX}/messages/forward`, // 转发邮件
  corpMailSearchMessages: `${CORP_MAIL_MAILAPI_PREFIX}/search`, // 信件搜索
  corpMailUpdateMessageInfos: `${CORP_MAIL_MAILAPI_PREFIX}/message/update`, // 更新信件
  corpMailListThreads: `${CORP_MAIL_MAILAPI_PREFIX}/threads`, // 会话列表
  corpMailGetThreadMessageInfos: `${CORP_MAIL_MAILAPI_PREFIX}/thread/infos`, // 会话信息获取
  corpMailMarkSeen: `${CORP_MAIL_MAILAPI_PREFIX}/seen`, // 已读
  corpMailCreateSign: `${CORP_MAIL_MAILAPI_PREFIX}/signatures/create`, // 添加签名
  corpMailDeleteSign: `${CORP_MAIL_MAILAPI_PREFIX}/signatures/delete`, // 删除签名
  corpMailUpdateSign: `${CORP_MAIL_MAILAPI_PREFIX}/signatures/update`, // 更新签名
  corpMailGetSign: `${CORP_MAIL_MAILAPI_PREFIX}/signatures`, // 获取签名
  corpMailGetUserAttrs: `${CORP_MAIL_MAILAPI_PREFIX}/user/attrs`, // 获取用户属性,
  corpMailUploadPrepare: `${CORP_MAIL_MAILAPI_PREFIX}/upload/prepare`, // 准备上传附件
  corpMailUpload: `${CORP_MAIL_MAILAPI_PREFIX}/upload/data`, // 上传附件
  corpMailListDeliverHistory: `${CORP_MAIL_MAILAPI_PREFIX}/delivery/histories`, // 投递状态
  corpMailRecallMessage: `${CORP_MAIL_MAILAPI_PREFIX}/message/recall`, // 信件召回
  corpMailEmptyFolder: `${CORP_MAIL_MAILAPI_PREFIX}/folder/empty`, // 清空文件夹
  corpMailListTags: `${CORP_MAIL_MAILAPI_PREFIX}/tags`, // 列出标签
  corpMailManageTags: `${CORP_MAIL_MAILAPI_PREFIX}/tags/manage`, // 标签管理
  corpMailUpdateMessageTags: `${CORP_MAIL_MAILAPI_PREFIX}/message/tags/update`, // 标签管理
  corpMailUpdateThreadTags: `${CORP_MAIL_MAILAPI_PREFIX}/thread/tags/update`, // 更新会话标签
  corpMailCancelDeliver: `${CORP_MAIL_MAILAPI_PREFIX}/devliver/cancel`, // 撤销投递
  corpMailGetMessageIfnos: `${CORP_MAIL_MAILAPI_PREFIX}/message/infos`, // 信件消息获取
  corpMailSetUserAttrs: `${CORP_MAIL_MAILAPI_PREFIX}/user/attrs/set`, // 用户属性设置
  corpMailRestoreDraft: `${CORP_MAIL_MAILAPI_PREFIX}/draft/restore`, // 恢复草稿箱
  corpMailEditMessage: `${CORP_MAIL_MAILAPI_PREFIX}/message/edit`, // 编辑草稿箱
  corpMailUserAuth2: `${CORP_MAIL_MAILAPI_PREFIX}/user/auth2`, // 编辑草稿箱
  corpMailGetAlias: `${CORP_MAIL_MAILAPI_PREFIX}/user/alias`, // 获取别名
  corpMailGetComposeInfo: `${CORP_MAIL_MAILAPI_PREFIX}/compose/info`, // 获取写信信息
  corpMailGetMessageData: `${CORP_MAIL_MAILAPI_PREFIX}/message/data`, // 获取信件附件二进制信息
  corpMailGetTmpAttachment: `${CORP_MAIL_MAILAPI_PREFIX}/compose/data`, // 获取写信页的临时附件地址
  corpMailCancelCompose: `${CORP_MAIL_MAILAPI_PREFIX}/composes/cancel`, // 取消写信，删除空间
  corpMailGetPackData: `${CORP_MAIL_MAILAPI_PREFIX}/pack/data`, // 下载多个附件
  corpCreateUserFolder: `${CORP_MAIL_MAILAPI_PREFIX}/folders/create`, // 创建文件夹
  corpUpdateUserFolder: `${CORP_MAIL_MAILAPI_PREFIX}/folders/update`, // 更新文件夹
  corpDeleteUserFolder: `${CORP_MAIL_MAILAPI_PREFIX}/folders/delete`, // 删除文件夹
  corpStatFolders: `${CORP_MAIL_MAILAPI_PREFIX}/folders/stats`, // 统计文件夹
  corpExchangeMails: `${CORP_MAIL_MAILAPI_PREFIX}/exchange/emailList`, // 往来邮件搜索
};
