export default {
  // 判断是否有session
  getHasSession: '/im/api/biz/session/exists',
  // 云信获取token
  getYunxinToken: '/cowork/api/biz/enter/emailContactList',
  // 获取云信服务号
  getYunxinServiceNum: '/im/api/biz/user/notify',
  // 群设置相关
  createTeam: '/im/api/biz/team/create',
  removeTeam: '/im/api/biz/team/remove',
  addMember: '/im/api/biz/team/add',
  removeMember: '/im/api/biz/team/kick',
  addManager: '/im/api/biz/team/manager/add',
  removeManager: '/im/api/biz/team/manager/remove',
  changeOwner: '/im/api/biz/team/owner/change',
  quitTeam: '/im/api/biz/team/quit',
  updateProfile: '/im/api/biz/team/profile/update',
  updateName: '/im/api/biz/team/profile/name/update',
  queryProfile: '/im/api/biz/team/profile/query',
  queryDetailProfile: '/im/api/biz/team/profile/query_detail',
  muteMessage: '/im/api/biz/team/attribute/mute',
  memberBelongs: '/im/api/biz/team/member/belongs',
  toggleSessionMute: '/im/api/biz/client/mute',
  // IM消息添加稍后处理
  addSessionLater: '/im/api/biz/session/later/add',
  // IM消息完成稍后处理
  completeSessionLater: '/im/api/biz/session/later/delete',
  // 获取IM消息稍后处理列表
  syncSessionLater: '/im/api/biz/session/later/list',
  // IM控制能否通过群号搜索群
  toggleTeamPublic: '/im/api/biz/team/public/setting',
  // IM通过tid查找群
  searchTeamPublic: '/im/api/biz/team/public/search',
  getTeamList: '/im/api/biz/team/member/in',
  getTeamMembers: '/im/api/biz/team/members',
  getCustomEmoji: '/im/api/biz/emoji/custom',
};
