const compDes = [
  {
    tags: {},
    filePath: '/Users/zhangpeiyuan/Documents/shellcandy/last/sirius-desktop/packages/web-common/src/components/UI/Pagination/index.tsx',
    description: '',
    displayName: 'Pagination',
    methods: [],
    props: {
      current: {
        defaultValue: { value: '1' },
        description: '当前页数',
        name: 'current',
        parent: { fileName: 'sirius-desktop/packages/web-common/src/components/UI/Pagination/index.tsx', name: 'SiriusPaginationProps' },
        declarations: [{ fileName: 'sirius-desktop/packages/web-common/src/components/UI/Pagination/index.tsx', name: 'SiriusPaginationProps' }],
        required: false,
        type: { name: 'number' },
      },
      defaultPageSize: {
        defaultValue: { value: '10' },
        description: '默认的每页条数',
        name: 'defaultPageSize',
        parent: { fileName: 'sirius-desktop/packages/web-common/src/components/UI/Pagination/index.tsx', name: 'SiriusPaginationProps' },
        declarations: [{ fileName: 'sirius-desktop/packages/web-common/src/components/UI/Pagination/index.tsx', name: 'SiriusPaginationProps' }],
        required: false,
        type: { name: 'number' },
      },
      disabled: {
        defaultValue: null,
        description: '禁用分页',
        name: 'disabled',
        parent: { fileName: 'sirius-desktop/packages/web-common/src/components/UI/Pagination/index.tsx', name: 'SiriusPaginationProps' },
        declarations: [{ fileName: 'sirius-desktop/packages/web-common/src/components/UI/Pagination/index.tsx', name: 'SiriusPaginationProps' }],
        required: false,
        type: { name: 'boolean' },
      },
      hideOnSinglePage: {
        defaultValue: { value: 'false' },
        description: '只有一页时是否隐藏分页器',
        name: 'hideOnSinglePage',
        parent: { fileName: 'sirius-desktop/packages/web-common/src/components/UI/Pagination/index.tsx', name: 'SiriusPaginationProps' },
        declarations: [{ fileName: 'sirius-desktop/packages/web-common/src/components/UI/Pagination/index.tsx', name: 'SiriusPaginationProps' }],
        required: false,
        type: { name: 'boolean' },
      },
      itemRender: {
        defaultValue: null,
        description: '用于自定义页码的结构，可用于优化 SEO',
        name: 'itemRender',
        parent: { fileName: 'sirius-desktop/packages/web-common/src/components/UI/Pagination/index.tsx', name: 'SiriusPaginationProps' },
        declarations: [{ fileName: 'sirius-desktop/packages/web-common/src/components/UI/Pagination/index.tsx', name: 'SiriusPaginationProps' }],
        required: false,
        type: { name: '(page: number, type: "page" | "prev" | "next", originalElement: ReactNode) => ReactNode' },
      },
      pageSize: {
        defaultValue: null,
        description: '每页条数',
        name: 'pageSize',
        parent: { fileName: 'sirius-desktop/packages/web-common/src/components/UI/Pagination/index.tsx', name: 'SiriusPaginationProps' },
        declarations: [{ fileName: 'sirius-desktop/packages/web-common/src/components/UI/Pagination/index.tsx', name: 'SiriusPaginationProps' }],
        required: false,
        type: { name: 'number' },
      },
      pageSizeOptions: {
        defaultValue: { value: '[10, 20, 50, 100]' },
        description: '指定每页可以显示多少条',
        name: 'pageSizeOptions',
        parent: { fileName: 'sirius-desktop/packages/web-common/src/components/UI/Pagination/index.tsx', name: 'SiriusPaginationProps' },
        declarations: [{ fileName: 'sirius-desktop/packages/web-common/src/components/UI/Pagination/index.tsx', name: 'SiriusPaginationProps' }],
        required: false,
        type: { name: 'string[]' },
      },
      responsive: {
        defaultValue: null,
        description: '当 size 未指定时，根据屏幕宽度自动调整尺寸',
        name: 'responsive',
        parent: { fileName: 'sirius-desktop/packages/web-common/src/components/UI/Pagination/index.tsx', name: 'SiriusPaginationProps' },
        declarations: [{ fileName: 'sirius-desktop/packages/web-common/src/components/UI/Pagination/index.tsx', name: 'SiriusPaginationProps' }],
        required: false,
        type: { name: 'boolean' },
      },
      showLessItems: {
        defaultValue: { value: 'false' },
        description: '是否显示较少页面内容',
        name: 'showLessItems',
        parent: { fileName: 'sirius-desktop/packages/web-common/src/components/UI/Pagination/index.tsx', name: 'SiriusPaginationProps' },
        declarations: [{ fileName: 'sirius-desktop/packages/web-common/src/components/UI/Pagination/index.tsx', name: 'SiriusPaginationProps' }],
        required: false,
        type: { name: 'boolean' },
      },
      showQuickJumper: {
        defaultValue: { value: 'false' },
        description: '是否可以快速跳转至某页',
        name: 'showQuickJumper',
        parent: { fileName: 'sirius-desktop/packages/web-common/src/components/UI/Pagination/index.tsx', name: 'SiriusPaginationProps' },
        declarations: [{ fileName: 'sirius-desktop/packages/web-common/src/components/UI/Pagination/index.tsx', name: 'SiriusPaginationProps' }],
        required: false,
        type: { name: 'boolean | { goButton: ReactNode; }' },
      },
      showSizeChanger: {
        defaultValue: null,
        description: '是否展示 pageSize 切换器，当 total 大于 50 时默认为 true',
        name: 'showSizeChanger',
        parent: { fileName: 'sirius-desktop/packages/web-common/src/components/UI/Pagination/index.tsx', name: 'SiriusPaginationProps' },
        declarations: [{ fileName: 'sirius-desktop/packages/web-common/src/components/UI/Pagination/index.tsx', name: 'SiriusPaginationProps' }],
        required: false,
        type: { name: 'boolean' },
      },
      showTitle: {
        defaultValue: { value: 'true' },
        description: '是否显示原生 tooltip 页码提示',
        name: 'showTitle',
        parent: { fileName: 'sirius-desktop/packages/web-common/src/components/UI/Pagination/index.tsx', name: 'SiriusPaginationProps' },
        declarations: [{ fileName: 'sirius-desktop/packages/web-common/src/components/UI/Pagination/index.tsx', name: 'SiriusPaginationProps' }],
        required: false,
        type: { name: 'boolean' },
      },
      showTotal: {
        defaultValue: null,
        description: '用于显示数据总量和当前数据顺序',
        name: 'showTotal',
        parent: { fileName: 'sirius-desktop/packages/web-common/src/components/UI/Pagination/index.tsx', name: 'SiriusPaginationProps' },
        declarations: [{ fileName: 'sirius-desktop/packages/web-common/src/components/UI/Pagination/index.tsx', name: 'SiriusPaginationProps' }],
        required: false,
        type: { name: '(total: number, range: [number, number]) => ReactNode' },
      },
      simple: {
        defaultValue: null,
        description: '当添加该属性时，显示为简单分页',
        name: 'simple',
        parent: { fileName: 'sirius-desktop/packages/web-common/src/components/UI/Pagination/index.tsx', name: 'SiriusPaginationProps' },
        declarations: [{ fileName: 'sirius-desktop/packages/web-common/src/components/UI/Pagination/index.tsx', name: 'SiriusPaginationProps' }],
        required: false,
        type: { name: 'boolean' },
      },
      size: {
        defaultValue: { value: "'default'" },
        description: '当为 small 时，是小尺寸分页',
        name: 'size',
        parent: { fileName: 'sirius-desktop/packages/web-common/src/components/UI/Pagination/index.tsx', name: 'SiriusPaginationProps' },
        declarations: [{ fileName: 'sirius-desktop/packages/web-common/src/components/UI/Pagination/index.tsx', name: 'SiriusPaginationProps' }],
        required: false,
        type: { name: 'enum', raw: '"default" | "small"', value: [{ value: '"default"' }, { value: '"small"' }] },
      },
      total: {
        defaultValue: { value: '0' },
        description: '数据总数',
        name: 'total',
        parent: { fileName: 'sirius-desktop/packages/web-common/src/components/UI/Pagination/index.tsx', name: 'SiriusPaginationProps' },
        declarations: [{ fileName: 'sirius-desktop/packages/web-common/src/components/UI/Pagination/index.tsx', name: 'SiriusPaginationProps' }],
        required: false,
        type: { name: 'number' },
      },
      onChange: {
        defaultValue: null,
        description: '页码或 pageSize 改变的回调，参数是改变后的页码及每页条数',
        name: 'onChange',
        parent: { fileName: 'sirius-desktop/packages/web-common/src/components/UI/Pagination/index.tsx', name: 'SiriusPaginationProps' },
        declarations: [{ fileName: 'sirius-desktop/packages/web-common/src/components/UI/Pagination/index.tsx', name: 'SiriusPaginationProps' }],
        required: false,
        type: { name: '(page: number, pageSize: number) => void' },
      },
      onShowSizeChange: {
        defaultValue: null,
        description: 'pageSize 变化的回调',
        name: 'onShowSizeChange',
        parent: { fileName: 'sirius-desktop/packages/web-common/src/components/UI/Pagination/index.tsx', name: 'SiriusPaginationProps' },
        declarations: [{ fileName: 'sirius-desktop/packages/web-common/src/components/UI/Pagination/index.tsx', name: 'SiriusPaginationProps' }],
        required: false,
        type: { name: '(current: number, size: number) => void' },
      },
    },
  },
];
export default compDes;
